#ifndef UI_H
#define UI_H

#include <vector>

#include <imgui.h>

struct Partition {
	int index;
	ImGuiDir direction;
	double fraction;
};

struct UILayout {
	std::vector<Partition> partitions;
	std::vector<int> windowIndices; //If windowIndices[0] is 1, then "start" goes in the window generated by the 1st partition
};
#endif