#ifndef BOP_H
#define BOP_H
char const *Bop_cfg = "// KittopiaTech - a Kopernicus Visual Editor\n"
"\n"
"@Kopernicus:NEEDS[!Kopernicus]\n"
"{\n"
"	Body\n"
"	{\n"
"		name = Bop\n"
"		barycenter = False\n"
"		identifier = Squad/Bop\n"
"		implements = \n"
"		finalizeOrbit = False\n"
"		randomMainMenuBody = False\n"
"		contractWeight = 30\n"
"		Properties\n"
"		{\n"
"			description = Bop is a small moon in the vicinity of Jool. In Kerbal mythology, Bop is believed to be the home of the Kraken, a mischievous creature said to play with the ships of hapless explorers, by spinning them out of control until torn asunder, then casting them into oblivion.\n"
"			radius = 65000\n"
"			geeASL = 0.0600204949543182\n"
"			mass = 3.72610898343278E+19\n"
"			gravParameter = 2486834944.41491\n"
"			rotates = True\n"
"			rotationPeriod = 544507.428516654\n"
"			tidallyLocked = True\n"
"			initialRotation = 230\n"
"			inverseRotThresholdAltitude = 100000\n"
"			albedo = 0.200000002980232\n"
"			emissivity = 0.800000011920929\n"
"			coreTemperatureOffset = 10\n"
"			timewarpAltitudeLimits = 0 24500 24500 24500 40000 60000 80000 100000\n"
"			sphereOfInfluence = 1221060.86284253\n"
"			solarRotationPeriod = False\n"
"			navballSwitchRadiusMult = 0.06\n"
"			navballSwitchRadiusMultLow = 0.055\n"
"			biomeMap = BUILTIN/bop_biome\n"
"			nonExactThreshold = -1\n"
"			exactSearch = False\n"
"			useTheInName = False\n"
"			displayName = Bop^N\n"
"			selectable = True\n"
"			RnDVisibility = Visible\n"
"			RnDRotation = False\n"
"			maxZoom = 60000\n"
"			ScienceValues\n"
"			{\n"
"				landedDataValue = 12 // Science multiplier for landed science.\n"
"				splashedDataValue = 1 // Science multiplier for splashed down science.\n"
"				flyingLowDataValue = 1 // Science multiplier for flying low science.\n"
"				flyingHighDataValue = 1 // Science multiplier for flying high science.\n"
"				inSpaceLowDataValue = 9 // Science multiplier for in space low science.\n"
"				inSpaceHighDataValue = 8 // Science multiplier for in space high science.\n"
"				recoveryValue = 8\n"
"				flyingAltitudeThreshold = 18000 // Altitude when \"flying at <body>\" transitions from/to \"from <body>'s upper atmosphere\"\n"
"				spaceAltitudeThreshold = 25000 // Altitude when \"in space low\" transitions from/to \"in space high\"\n"
"			}\n"
"			Biomes\n"
"			{\n"
"				Value\n"
"				{\n"
"					name = Peaks // The name of this biome.\n"
"					displayName = Peaks // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.866666675,0.800000012,0.654901981,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Ridges // The name of this biome.\n"
"					displayName = Ridges // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.768627465,0.698039234,0.545098066,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Poles // The name of this biome.\n"
"					displayName = Poles // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.960784316,0.886274517,0.725490212,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Slopes // The name of this biome.\n"
"					displayName = Slopes // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.68235296,0.615686297,0.470588237,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Valley // The name of this biome.\n"
"					displayName = Valley // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.592156887,0.549019635,0.450980395,1 // The color of the biome on the biome map.\n"
"				}\n"
"			}\n"
"		}\n"
"		Orbit\n"
"		{\n"
"			referenceBody = Jool // The body that this body is orbiting around.\n"
"			inclination = 15\n"
"			eccentricity = 0.234999999403954\n"
"			semiMajorAxis = 128500000 // The altitude of the highest point in the orbit\n"
"			longitudeOfAscendingNode = 10 // The position of the highest point on the orbit circle\n"
"			argumentOfPeriapsis = 25\n"
"			meanAnomalyAtEpoch = 0.899999976158142\n"
"			meanAnomalyAtEpochD = 51.5662001957363\n"
"			epoch = 0\n"
"			color = 0.729411781,0.627451003,0.494117647,0.501960814 // The color of the orbit line in the Tracking Station\n"
"			nodeColor = 0.729411781,0.627451003,0.494117647,0.501960814 // The color of the circle that marks the planets current position on the orbit\n"
"			mode = REDRAW_AND_RECALCULATE\n"
"			icon = ALL\n"
"			cameraSmaRatioBounds = 0.12 12\n"
"			period = 544507.428516654\n"
"		}\n"
"		ScaledVersion\n"
"		{\n"
"			type = Vacuum\n"
"			fadeStart = 135000\n"
"			fadeEnd = 140000\n"
"			sphericalModel = False\n"
"			deferMesh = False\n"
"			invisible = False\n"
"			Material\n"
"			{\n"
"				color = 1,1,1,1\n"
"				specColor = 0,0,0,1\n"
"				shininess = 0.078125\n"
"				texture = BUILTIN/gp1minormoon100\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				normals = BUILTIN/gp1minormoon101\n"
"				bumpMapScale = 1,1\n"
"				bumpMapOffset = 0,0\n"
"				opacity = 1\n"
"				resourceMapScale = 1,1\n"
"				resourceMapOffset = 0,0\n"
"			}\n"
"		}\n"
"		PQS\n"
"		{\n"
"			minLevel = 2\n"
"			maxLevel = 6\n"
"			minDetailDistance = 8\n"
"			maxQuadLengthsPerFrame = 0.03\n"
"			fadeStart = 140000\n"
"			fadeEnd = 145000\n"
"			deactivateAltitude = 180000\n"
"			mapMaxHeight = 30000\n"
"			materialType = Vacuum\n"
"			PhysicsMaterial\n"
"			{\n"
"				bounceCombine = Average\n"
"				frictionCombine = Maximum\n"
"				bounciness = 0\n"
"				staticFriction = 0.8\n"
"				dynamicFriction = 0.6\n"
"			}\n"
"			Material\n"
"			{\n"
"				saturation = 1\n"
"				contrast = 1.2\n"
"				tintColor = 1,1,1,0\n"
"				texTiling = 1024\n"
"				texPower = 0.75\n"
"				multiPower = 0.75\n"
"				groundTexStart = 0\n"
"				groundTexEnd = 20000\n"
"				steepTiling = 10\n"
"				steepPower = 0.76\n"
"				steepTexStart = 200000\n"
"				steepTexEnd = 300000\n"
"				deepTex = BUILTIN/RockyGround\n"
"				deepTexScale = 1,1\n"
"				deepTexOffset = 0,0\n"
"				deepMultiTex = BUILTIN/distantground\n"
"				deepMultiTexScale = 1,1\n"
"				deepMultiTexOffset = 0,0\n"
"				deepMultiFactor = 8\n"
"				mainTex = BUILTIN/RockyGround\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				mainMultiTex = BUILTIN/distantground\n"
"				mainMultiTexScale = 1,1\n"
"				mainMultiTexOffset = 0,0\n"
"				mainMultiFactor = 10\n"
"				highTex = BUILTIN/RockyGround\n"
"				highTexScale = 1,1\n"
"				highTexOffset = 0,0\n"
"				highMultiTex = BUILTIN/distantground\n"
"				highMultiTexScale = 1,1\n"
"				highMultiTexOffset = 0,0\n"
"				highMultiFactor = 12\n"
"				snowTex = BUILTIN/RockyGround\n"
"				snowTexScale = 1,1\n"
"				snowTexOffset = 0,0\n"
"				snowMultiTex = BUILTIN/distantground\n"
"				snowMultiTexScale = 1,1\n"
"				snowMultiTexOffset = 0,0\n"
"				snowMultiFactor = 14\n"
"				steepTex = BUILTIN/terrain_rock00\n"
"				steepTexScale = 1,1\n"
"				steepTexOffset = 0,0\n"
"				deepStart = 0\n"
"				deepEnd = 0.01\n"
"				mainLoStart = 0\n"
"				mainLoEnd = 0.05\n"
"				mainHiStart = 0.1\n"
"				mainHiEnd = 0.15\n"
"				hiLoStart = 0.1\n"
"				hiLoEnd = 0.15\n"
"				hiHiStart = 0.2\n"
"				hiHiEnd = 0.25\n"
"				snowStart = 0.2\n"
"				snowEnd = 0.25\n"
"				planetOpacity = 1\n"
"			}\n"
"			FallbackMaterial\n"
"			{\n"
"				saturation = 1\n"
"				contrast = 1.2\n"
"				tintColor = 1,1,1,0\n"
"				texTiling = 1024\n"
"				texPower = 0.75\n"
"				multiPower = 0.75\n"
"				groundTexStart = 0\n"
"				groundTexEnd = 20000\n"
"				multiFactor = 0.5\n"
"				mainTex = BUILTIN/RockyGround\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				planetOpacity = 1\n"
"			}\n"
"			Mods\n"
"			{\n"
"				FlattenArea\n"
"				{\n"
"					DEBUG_showColors = False\n"
"					flattenTo = 900\n"
"					innerRadius = 15000\n"
"					outerRadius = 35000\n"
"					position = -19468.5,5737.08887,61828.1289\n"
"					smoothEnd = 0\n"
"					smoothStart = 0\n"
"					order = 11\n"
"					enabled = False\n"
"					name = _Crater1\n"
"				}\n"
"				MapDecal\n"
"				{\n"
"					absolute = False\n"
"					absoluteOffset = 0\n"
"					angle = 0\n"
"					colorMap = BUILTIN/bigcrater\n"
"					cullBlack = False\n"
"					DEBUG_HighlightInclusion = False\n"
"					heightMapDeformity = 10\n"
"					position = -19468.5,5737.08887,61828.1289\n"
"					removeScatter = False\n"
"					radius = 65000\n"
"					smoothColor = 0.125\n"
"					smoothHeight = 0.125\n"
"					useAlphaHeightSmoothing = False\n"
"					order = 120\n"
"					enabled = True\n"
"					name = _Crater1\n"
"				}\n"
"				VertexSimplexHeightAbsolute\n"
"				{\n"
"					deformity = 24000\n"
"					frequency = 0.800000011920929\n"
"					octaves = 3\n"
"					persistence = 0.5\n"
"					seed = 3339066\n"
"					order = 10\n"
"					enabled = True\n"
"					name = _Height\n"
"				}\n"
"				VertexHeightNoise\n"
"				{\n"
"					deformity = 600\n"
"					frequency = 5\n"
"					octaves = 8\n"
"					persistence = 0.5\n"
"					seed = 45756\n"
"					noiseType = RiggedMultifractal\n"
"					mode = Low\n"
"					lacunarity = 2.5\n"
"					order = 19\n"
"					enabled = True\n"
"					name = _Height\n"
"				}\n"
"				FlattenArea\n"
"				{\n"
"					DEBUG_showColors = False\n"
"					flattenTo = 2200\n"
"					innerRadius = 4000\n"
"					outerRadius = 15000\n"
"					position = 2000,5737.08887,61828.1289\n"
"					smoothEnd = 0\n"
"					smoothStart = 0\n"
"					order = 13\n"
"					enabled = False\n"
"					name = _Crater2\n"
"				}\n"
"				MapDecal\n"
"				{\n"
"					absolute = False\n"
"					absoluteOffset = 0\n"
"					angle = 0\n"
"					colorMap = BUILTIN/bigcrater\n"
"					cullBlack = False\n"
"					DEBUG_HighlightInclusion = False\n"
"					heightMapDeformity = 10\n"
"					position = 2000,5737.08887,61828.1289\n"
"					removeScatter = False\n"
"					radius = 20000\n"
"					smoothColor = 0.125\n"
"					smoothHeight = 0.125\n"
"					useAlphaHeightSmoothing = False\n"
"					order = 121\n"
"					enabled = True\n"
"					name = _Crater2\n"
"				}\n"
"				AltitudeAlpha\n"
"				{\n"
"					atmosphereDepth = 8000\n"
"					invert = False\n"
"					order = 999999999\n"
"					enabled = True\n"
"					name = _Material_ModProjection\n"
"				}\n"
"				VertexSimplexNoiseColor\n"
"				{\n"
"					blend = 1\n"
"					colorStart = 0.171641767,0.15043062,0.130652696,1\n"
"					colorEnd = 0.291044772,0.240739986,0.21285364,1\n"
"					frequency = 1\n"
"					octaves = 6\n"
"					persistence = 0.5\n"
"					seed = 64564\n"
"					order = 100\n"
"					enabled = True\n"
"					name = _Color\n"
"				}\n"
"				LandControl\n"
"				{\n"
"					altitudeBlend = 0\n"
"					altitudeFrequency = 1\n"
"					altitudeOctaves = 1\n"
"					altitudePersistance = 1\n"
"					altitudeSeed = 1\n"
"					createColors = False\n"
"					createScatter = True\n"
"					latitudeBlend = 0\n"
"					latitudeFrequency = 1\n"
"					latitudeOctaves = 1\n"
"					latitudePersistance = 1\n"
"					latitudeSeed = 1\n"
"					longitudeBlend = 0\n"
"					longitudeFrequency = 1\n"
"					longitudeOctaves = 1\n"
"					longitudePersistance = 1\n"
"					longitudeSeed = 1\n"
"					useHeightMap = False\n"
"					vHeightMax = 10000\n"
"					order = 999999\n"
"					enabled = True\n"
"					name = Scatter\n"
"					Scatters\n"
"					{\n"
"						Value\n"
"						{\n"
"							name = boulder\n"
"							materialType = BumpedDiffuse\n"
"							material = BUILTIN/brown_cliff\n"
"							mesh = BUILTIN/boulder\n"
"							castShadows = True\n"
"							densityFactor = 1\n"
"							maxCache = 512\n"
"							maxCacheDelta = 32\n"
"							maxLevelOffset = 0\n"
"							maxScale = 3\n"
"							maxScatter = 20\n"
"							maxSpeed = 1000\n"
"							minScale = 0.5\n"
"							recieveShadows = True\n"
"							seed = 231123\n"
"							verticalOffset = 0\n"
"							instancing = False\n"
"							rotation = 0 360\n"
"							useBetterDensity = False\n"
"							spawnChance = 1\n"
"							ignoreDensityGameSetting = False\n"
"							densityVariance = -0.5 0.5\n"
"							delete = False\n"
"							Material\n"
"							{\n"
"								color = 1,1,1,1\n"
"								mainTex = BUILTIN/brown_cliff\n"
"								mainTexScale = 1,1\n"
"								mainTexOffset = 0,0\n"
"								bumpMap = BUILTIN/bouldernormal\n"
"								bumpMapScale = 1,1\n"
"								bumpMapOffset = 0,0\n"
"							}\n"
"						}\n"
"					}\n"
"					LandClasses\n"
"					{\n"
"						Value\n"
"						{\n"
"							alterApparentHeight = 0\n"
"							alterRealHeight = 0\n"
"							color = 0,0,0,0\n"
"							coverageBlend = 0\n"
"							coverageFrequency = 1\n"
"							coverageOctaves = 1\n"
"							coveragePersistance = 1\n"
"							coverageSeed = 1\n"
"							name = Base\n"
"							latDelta = 1\n"
"							latitudeDouble = False\n"
"							lonDelta = 1\n"
"							minimumRealHeight = 0\n"
"							noiseBlend = 0\n"
"							noiseColor = 0,0,0,0\n"
"							noiseFrequency = 1\n"
"							noiseOctaves = 1\n"
"							noisePersistance = 1\n"
"							noiseSeed = 1\n"
"							delete = False\n"
"							altitudeRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							latitudeDoubleRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							latitudeRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							longitudeRange\n"
"							{\n"
"								endEnd = 2\n"
"								endStart = 2\n"
"								startEnd = -1\n"
"								startStart = -1\n"
"							}\n"
"							Scatters\n"
"							{\n"
"								Value\n"
"								{\n"
"									density = 1\n"
"									scatterName = boulder\n"
"									delete = False\n"
"								}\n"
"							}\n"
"						}\n"
"					}\n"
"				}\n"
"				City\n"
"				{\n"
"					debugOrientated = False\n"
"					frameDelta = 1\n"
"					randomizeOnSphere = False\n"
"					reorientToSphere = True\n"
"					reorientFinalAngle = 0\n"
"					reorientInitialUp = 0,1,0\n"
"					repositionRadial = -13172.3496,73416.7266,25863.1309\n"
"					repositionRadiusOffset = 13949.7001953125\n"
"					repositionToSphere = True\n"
"					repositionToSphereSurface = False\n"
"					repositionToSphereSurfaceAddHeight = False\n"
"					commnetStation = False\n"
"					isKSC = False\n"
"					order = 100\n"
"					enabled = True\n"
"					name = DeadKraken\n"
"				}\n"
"				City\n"
"				{\n"
"					debugOrientated = False\n"
"					frameDelta = 1\n"
"					randomizeOnSphere = True\n"
"					reorientToSphere = True\n"
"					reorientFinalAngle = 45\n"
"					reorientInitialUp = 0,1,0\n"
"					repositionRadial = 513856,-290549,-122798\n"
"					repositionRadiusOffset = 2948.5\n"
"					repositionToSphere = True\n"
"					repositionToSphereSurface = True\n"
"					repositionToSphereSurfaceAddHeight = False\n"
"					commnetStation = False\n"
"					isKSC = False\n"
"					order = 100\n"
"					enabled = True\n"
"					name = Randolith\n"
"					LOD\n"
"					{\n"
"						Value\n"
"						{\n"
"							visibleRange = 10000\n"
"							scale = 0,0,0\n"
"							delete = False\n"
"						}\n"
"					}\n"
"				}\n"
"			}\n"
"		}\n"
"		Debug\n"
"		{\n"
"			exportMesh = True // Whether Kopernicus should save a .bin file with the ScaledSpace mesh.\n"
"			update = False // Setting this to true will force Kopernicus to update the ScaledSpace mesh.\n"
"			showSOI = False\n"
"		}\n"
"	}\n"
"}\n";
#endif