#include <string>
#ifndef DRES_H
#define DRES_H
std::string Dres_cfg = "// KittopiaTech - a Kopernicus Visual Editor\n"
"\n"
"@Kopernicus:NEEDS[!Kopernicus]\n"
"{\n"
"	Body\n"
"	{\n"
"		name = Dres\n"
"		barycenter = False\n"
"		identifier = Squad/Dres\n"
"		implements = \n"
"		finalizeOrbit = False\n"
"		randomMainMenuBody = False\n"
"		contractWeight = 30\n"
"		Properties\n"
"		{\n"
"			description = Dres is a very small planet. It was the first planet considered to be a dwarf. It’s orbit is highly irregular and together with it’s size it took a long time to discover since half the time it was not where scientists expected to find a planet.Due to its nature of frequenting the bad parts of space. This dwarf planet was officially labeled as “Not to be trusted” by the scientific community.\n"
"			radius = 138000\n"
"			geeASL = 0.115039284567105\n"
"			mass = 3.21909365785247E+20\n"
"			gravParameter = 21484488600\n"
"			rotates = True\n"
"			rotationPeriod = 34800\n"
"			tidallyLocked = False\n"
"			initialRotation = 25\n"
"			inverseRotThresholdAltitude = 100000\n"
"			albedo = 0.12\n"
"			emissivity = 0.88\n"
"			coreTemperatureOffset = 0\n"
"			timewarpAltitudeLimits = 0 10000 10000 30000 50000 100000 200000 300000\n"
"			sphereOfInfluence = 32832839.5767762\n"
"			solarRotationPeriod = False\n"
"			navballSwitchRadiusMult = 0.06\n"
"			navballSwitchRadiusMultLow = 0.055\n"
"			biomeMap = BUILTIN/dres_biome\n"
"			nonExactThreshold = -1\n"
"			exactSearch = False\n"
"			useTheInName = False\n"
"			displayName = Dres^N\n"
"			selectable = True\n"
"			RnDVisibility = Visible\n"
"			RnDRotation = False\n"
"			maxZoom = 60000\n"
"			ScienceValues\n"
"			{\n"
"				landedDataValue = 8 // Science multiplier for landed science.\n"
"				splashedDataValue = 1 // Science multiplier for splashed down science.\n"
"				flyingLowDataValue = 1 // Science multiplier for flying low science.\n"
"				flyingHighDataValue = 1 // Science multiplier for flying high science.\n"
"				inSpaceLowDataValue = 7 // Science multiplier for in space low science.\n"
"				inSpaceHighDataValue = 6 // Science multiplier for in space high science.\n"
"				recoveryValue = 6\n"
"				flyingAltitudeThreshold = 18000 // Altitude when \"flying at <body>\" transitions from/to \"from <body>'s upper atmosphere\"\n"
"				spaceAltitudeThreshold = 25000 // Altitude when \"in space low\" transitions from/to \"in space high\"\n"
"			}\n"
"			Biomes\n"
"			{\n"
"				Value\n"
"				{\n"
"					name = Poles // The name of this biome.\n"
"					displayName = Poles // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.972549021,0.929411769,0.862745106,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Midlands // The name of this biome.\n"
"					displayName = Midlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.525490224,0.505882382,0.470588237,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Lowlands // The name of this biome.\n"
"					displayName = Lowlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.458823532,0.443137258,0.419607848,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Ridges // The name of this biome.\n"
"					displayName = Ridges // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.694117665,0.654901981,0.592156887,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Highlands // The name of this biome.\n"
"					displayName = Highlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.819607854,0.760784328,0.670588255,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Impact Craters // The name of this biome.\n"
"					displayName = Impact Craters // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.380392164,0.36470589,0.349019617,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Impact Ejecta // The name of this biome.\n"
"					displayName = Impact Ejecta // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.611764729,0.580392182,0.533333361,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Canyons // The name of this biome.\n"
"					displayName = Canyons // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.333333343,0.321568638,0.305882365,1 // The color of the biome on the biome map.\n"
"				}\n"
"			}\n"
"		}\n"
"		Orbit\n"
"		{\n"
"			referenceBody = Sun // The body that this body is orbiting around.\n"
"			inclination = 5\n"
"			eccentricity = 0.145\n"
"			semiMajorAxis = 40839348203 // The altitude of the highest point in the orbit\n"
"			longitudeOfAscendingNode = 280 // The position of the highest point on the orbit circle\n"
"			argumentOfPeriapsis = 90\n"
"			meanAnomalyAtEpoch = 3.14000010490417\n"
"			meanAnomalyAtEpochD = 179.908753681645\n"
"			epoch = 0\n"
"			color = 0.352941185,0.266666681,0.196078435,0.501960814 // The color of the orbit line in the Tracking Station\n"
"			nodeColor = 0.352941185,0.266666681,0.196078435,0.501960814 // The color of the circle that marks the planets current position on the orbit\n"
"			mode = REDRAW_AND_RECALCULATE\n"
"			icon = ALL\n"
"			cameraSmaRatioBounds = 0.03 25\n"
"			period = 47893063.1385932\n"
"		}\n"
"		ScaledVersion\n"
"		{\n"
"			type = Vacuum\n"
"			fadeStart = 8000\n"
"			fadeEnd = 39000\n"
"			sphericalModel = False\n"
"			deferMesh = False\n"
"			invisible = False\n"
"			Material\n"
"			{\n"
"				color = 1,1,1,1\n"
"				specColor = 0,0,0,1\n"
"				shininess = 0.078125\n"
"				texture = BUILTIN/dwarfplanet100\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				normals = BUILTIN/dwarfplanet101\n"
"				bumpMapScale = 1,1\n"
"				bumpMapOffset = 0,0\n"
"				opacity = 1\n"
"				resourceMapScale = 1,1\n"
"				resourceMapOffset = 0,0\n"
"			}\n"
"		}\n"
"		PQS\n"
"		{\n"
"			minLevel = 2\n"
"			maxLevel = 9\n"
"			minDetailDistance = 8\n"
"			maxQuadLengthsPerFrame = 0.03\n"
"			fadeStart = 40000\n"
"			fadeEnd = 160000\n"
"			deactivateAltitude = 170000\n"
"			mapMaxHeight = 8000\n"
"			materialType = AtmosphericTriplanarZoomRotation\n"
"			PhysicsMaterial\n"
"			{\n"
"				bounceCombine = Multiply\n"
"				frictionCombine = Maximum\n"
"				bounciness = 0\n"
"				staticFriction = 0.9\n"
"				dynamicFriction = 0.9\n"
"			}\n"
"			Material\n"
"			{\n"
"				factor = 10\n"
"				factorBlendWidth = 0.05\n"
"				factorRotation = 180\n"
"				saturation = 1\n"
"				contrast = 1\n"
"				tintColor = 1,1,1,0\n"
"				specularColor = 0.0367646813,0.0367646813,0.0367646813,0.200000003\n"
"				albedoBrightness = 1\n"
"				steepPower = 3\n"
"				steepTexStart = 500\n"
"				steepTexEnd = 1000000\n"
"				steepTex = BUILTIN/dresSteepDiffuse\n"
"				steepTexScale = 1,1\n"
"				steepTexOffset = 0,0\n"
"				steepBumpMap = BUILTIN/DresSteepNRM\n"
"				steepBumpMapScale = 1,1\n"
"				steepBumpMapOffset = 0,0\n"
"				steepNearTiling = 500\n"
"				steepTiling = 125\n"
"				lowTexScale = 1,1\n"
"				lowTexOffset = 0,0\n"
"				lowTiling = 38000\n"
"				midTex = BUILTIN/dresMid\n"
"				midTexScale = 1,1\n"
"				midTexOffset = 0,0\n"
"				midTiling = 40000\n"
"				midBumpMap = BUILTIN/dresMidNRM\n"
"				midBumpMapScale = 1,1\n"
"				midBumpMapOffset = 0,0\n"
"				midBumpTiling = 40000\n"
"				highTex = BUILTIN/dresHigh\n"
"				highTexScale = 1,1\n"
"				highTexOffset = 0,0\n"
"				highTiling = 40000\n"
"				lowStart = 0\n"
"				lowEnd = 0.3\n"
"				highStart = 0.8\n"
"				highEnd = 1\n"
"				globalDensity = -5E-06\n"
"				fogColorRampScale = 1,1\n"
"				fogColorRampOffset = 0,0\n"
"				planetOpacity = 0\n"
"				oceanFogDistance = 1000\n"
"			}\n"
"			FallbackMaterial\n"
"			{\n"
"				saturation = 1.62\n"
"				contrast = 1.9\n"
"				tintColor = 1,1,1,0\n"
"				texTiling = 1024\n"
"				texPower = 0.75\n"
"				multiPower = 0.75\n"
"				groundTexStart = 0\n"
"				groundTexEnd = 20000\n"
"				multiFactor = 0.5\n"
"				mainTex = BUILTIN/RockyGround\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				planetOpacity = 1\n"
"			}\n"
"			Mods\n"
"			{\n"
"				VertexSimplexNoiseColor\n"
"				{\n"
"					blend = 1\n"
"					colorStart = 0.792452812,0.763296545,0.743858993,1\n"
"					colorEnd = 0.160377383,0.160377383,0.160377383,1\n"
"					frequency = 2\n"
"					octaves = 12\n"
"					persistence = 0.5\n"
"					seed = 346434\n"
"					order = 200\n"
"					enabled = True\n"
"					name = _Color\n"
"				}\n"
"				HeightColorMap\n"
"				{\n"
"					blend = 0.7\n"
"					order = 201\n"
"					enabled = True\n"
"					name = _Color\n"
"					LandClasses\n"
"					{\n"
"						Value\n"
"						{\n"
"							name = AbyPl\n"
"							color = 0,0,0,1\n"
"							altitudeStart = 0\n"
"							altitudeEnd = 0.5\n"
"							lerpToNext = True\n"
"							delete = False\n"
"						}\n"
"						Value\n"
"						{\n"
"							name = Beach\n"
"							color = 0.164179087,0.164179087,0.164179087,1\n"
"							altitudeStart = 0.5\n"
"							altitudeEnd = 0.550000011920929\n"
"							lerpToNext = True\n"
"							delete = False\n"
"						}\n"
"						Value\n"
"						{\n"
"							name = Beach\n"
"							color = 0.373134315,0.373134315,0.373134315,1\n"
"							altitudeStart = 0.550000011920929\n"
"							altitudeEnd = 1\n"
"							lerpToNext = False\n"
"							delete = False\n"
"						}\n"
"					}\n"
"				}\n"
"				AltitudeAlpha\n"
"				{\n"
"					atmosphereDepth = 4000\n"
"					invert = False\n"
"					order = 999999999\n"
"					enabled = False\n"
"					name = _Material_ModProjection\n"
"				}\n"
"				AerialPerspectiveMaterial\n"
"				{\n"
"					atmosphereDepth = 150000\n"
"					DEBUG_SetEveryFrame = True\n"
"					globalDensity = -1E-05\n"
"					heightFalloff = 6.75\n"
"					oceanDepth = 0\n"
"					order = 100\n"
"					enabled = True\n"
"					name = _Material_AerialPerspective\n"
"				}\n"
"				VertexHeightMap\n"
"				{\n"
"					map = BUILTIN/dwarfplanet1_height\n"
"					offset = 0\n"
"					deformity = 4000\n"
"					scaleDeformityByRadius = False\n"
"					order = 20\n"
"					enabled = True\n"
"					name = _HeightNoise\n"
"				}\n"
"				VertexSimplexHeight\n"
"				{\n"
"					deformity = 1700\n"
"					frequency = 4\n"
"					octaves = 12\n"
"					persistence = 0.5\n"
"					seed = 674624\n"
"					order = 21\n"
"					enabled = True\n"
"					name = _HeightNoise\n"
"				}\n"
"				FlattenOcean\n"
"				{\n"
"					oceanRadius = 1\n"
"					order = 25\n"
"					enabled = True\n"
"					name = _HeightNoise\n"
"				}\n"
"				VertexHeightNoise\n"
"				{\n"
"					deformity = 1000\n"
"					frequency = 2\n"
"					octaves = 4\n"
"					persistence = 0.5\n"
"					seed = 590676637\n"
"					noiseType = RiggedMultifractal\n"
"					mode = Low\n"
"					lacunarity = 2.5\n"
"					order = 22\n"
"					enabled = True\n"
"					name = _HeightNoise\n"
"				}\n"
"				VertexSimplexHeightAbsolute\n"
"				{\n"
"					deformity = 400\n"
"					frequency = 18\n"
"					octaves = 6\n"
"					persistence = 0.5\n"
"					seed = 4234532\n"
"					order = 30\n"
"					enabled = True\n"
"					name = _FineDetail\n"
"				}\n"
"				City\n"
"				{\n"
"					debugOrientated = False\n"
"					frameDelta = 1\n"
"					randomizeOnSphere = True\n"
"					reorientToSphere = True\n"
"					reorientFinalAngle = 45\n"
"					reorientInitialUp = 0,1,0\n"
"					repositionRadial = 513856,-290549,-122798\n"
"					repositionRadiusOffset = 2948.5\n"
"					repositionToSphere = True\n"
"					repositionToSphereSurface = True\n"
"					repositionToSphereSurfaceAddHeight = False\n"
"					commnetStation = False\n"
"					isKSC = False\n"
"					order = 100\n"
"					enabled = True\n"
"					name = Randolith\n"
"					LOD\n"
"					{\n"
"						Value\n"
"						{\n"
"							visibleRange = 10000\n"
"							scale = 0,0,0\n"
"							delete = False\n"
"						}\n"
"					}\n"
"				}\n"
"			}\n"
"		}\n"
"		Debug\n"
"		{\n"
"			exportMesh = True // Whether Kopernicus should save a .bin file with the ScaledSpace mesh.\n"
"			update = False // Setting this to true will force Kopernicus to update the ScaledSpace mesh.\n"
"			showSOI = False\n"
"		}\n"
"	}\n"
"}\n";
#endif