#include <string>
#ifndef IKE_H
#define IKE_H
std::string Ike_cfg = "// KittopiaTech - a Kopernicus Visual Editor\n"
"\n"
"@Kopernicus:NEEDS[!Kopernicus]\n"
"{\n"
"	Body\n"
"	{\n"
"		name = Ike\n"
"		barycenter = False\n"
"		identifier = Squad/Ike\n"
"		implements = \n"
"		finalizeOrbit = False\n"
"		randomMainMenuBody = False\n"
"		contractWeight = 30\n"
"		Properties\n"
"		{\n"
"			description = Ike is a relatively large, grey object occasionally seen orbiting Duna. Scientists have postulated that Ike is seemingly perfectly positioned to sneakily interfere with any object that presumes to come orbiting near its parent.\n"
"			radius = 130000\n"
"			geeASL = 0.112038263210561\n"
"			mass = 2.78216152235874E+20\n"
"			gravParameter = 18568368573.144\n"
"			rotates = True\n"
"			rotationPeriod = 65517.8621348081\n"
"			tidallyLocked = True\n"
"			initialRotation = 0\n"
"			inverseRotThresholdAltitude = 100000\n"
"			albedo = 0.14\n"
"			emissivity = 0.86\n"
"			coreTemperatureOffset = 2\n"
"			timewarpAltitudeLimits = 0 5000 5000 10000 25000 50000 100000 200000\n"
"			sphereOfInfluence = 1049598.93931162\n"
"			solarRotationPeriod = False\n"
"			navballSwitchRadiusMult = 0.06\n"
"			navballSwitchRadiusMultLow = 0.055\n"
"			biomeMap = BUILTIN/ike_biome\n"
"			nonExactThreshold = -1\n"
"			exactSearch = False\n"
"			useTheInName = False\n"
"			displayName = Ike^N\n"
"			selectable = True\n"
"			RnDVisibility = Visible\n"
"			RnDRotation = False\n"
"			maxZoom = 60000\n"
"			ScienceValues\n"
"			{\n"
"				landedDataValue = 8 // Science multiplier for landed science.\n"
"				splashedDataValue = 1 // Science multiplier for splashed down science.\n"
"				flyingLowDataValue = 1 // Science multiplier for flying low science.\n"
"				flyingHighDataValue = 1 // Science multiplier for flying high science.\n"
"				inSpaceLowDataValue = 7 // Science multiplier for in space low science.\n"
"				inSpaceHighDataValue = 5 // Science multiplier for in space high science.\n"
"				recoveryValue = 5\n"
"				flyingAltitudeThreshold = 18000 // Altitude when \"flying at <body>\" transitions from/to \"from <body>'s upper atmosphere\"\n"
"				spaceAltitudeThreshold = 50000 // Altitude when \"in space low\" transitions from/to \"in space high\"\n"
"			}\n"
"			Biomes\n"
"			{\n"
"				Value\n"
"				{\n"
"					name = Polar Lowlands // The name of this biome.\n"
"					displayName = Polar Lowlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.474509805,0.466666669,0.4627451,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Midlands // The name of this biome.\n"
"					displayName = Midlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.576470613,0.576470613,0.576470613,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Eastern Mountain Ridge // The name of this biome.\n"
"					displayName = Eastern Mountain Ridge // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 1,1,1,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Western Mountain Ridge // The name of this biome.\n"
"					displayName = Western Mountain Ridge // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.925490201,0.925490201,0.925490201,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Lowlands // The name of this biome.\n"
"					displayName = Lowlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.407843143,0.407843143,0.407843143,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = South Eastern Mountain Range // The name of this biome.\n"
"					displayName = South Eastern Mountain Range // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.854901969,0.854901969,0.854901969,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = South Pole // The name of this biome.\n"
"					displayName = South Pole // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.517647088,0.517647088,0.517647088,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Central Mountain Range // The name of this biome.\n"
"					displayName = Central Mountain Range // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.800000012,0.800000012,0.800000012,1 // The color of the biome on the biome map.\n"
"				}\n"
"			}\n"
"		}\n"
"		Orbit\n"
"		{\n"
"			referenceBody = Duna // The body that this body is orbiting around.\n"
"			inclination = 0.200000002980232\n"
"			eccentricity = 0.0299999993294477\n"
"			semiMajorAxis = 3200000 // The altitude of the highest point in the orbit\n"
"			longitudeOfAscendingNode = 0 // The position of the highest point on the orbit circle\n"
"			argumentOfPeriapsis = 0\n"
"			meanAnomalyAtEpoch = 1.70000004768372\n"
"			meanAnomalyAtEpochD = 97.4028279043159\n"
"			epoch = 0\n"
"			color = 0.521568656,0.541176498,0.603921592,0.501960814 // The color of the orbit line in the Tracking Station\n"
"			nodeColor = 0.521568656,0.541176498,0.603921592,0.501960814 // The color of the circle that marks the planets current position on the orbit\n"
"			mode = REDRAW_AND_RECALCULATE\n"
"			icon = ALL\n"
"			cameraSmaRatioBounds = 0.03 25\n"
"			period = 65517.8621348081\n"
"		}\n"
"		ScaledVersion\n"
"		{\n"
"			type = Vacuum\n"
"			fadeStart = 20000\n"
"			fadeEnd = 25000\n"
"			sphericalModel = False\n"
"			deferMesh = False\n"
"			invisible = False\n"
"			Material\n"
"			{\n"
"				color = 1,1,1,1\n"
"				specColor = 0,0,0,1\n"
"				shininess = 0.078125\n"
"				texture = BUILTIN/desertplanetmoon00\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				normals = BUILTIN/desertplanetmoon01\n"
"				bumpMapScale = 1,1\n"
"				bumpMapOffset = 0,0\n"
"				opacity = 1\n"
"				resourceMapScale = 1,1\n"
"				resourceMapOffset = 0,0\n"
"			}\n"
"		}\n"
"		PQS\n"
"		{\n"
"			minLevel = 2\n"
"			maxLevel = 7\n"
"			minDetailDistance = 8\n"
"			maxQuadLengthsPerFrame = 0.03\n"
"			fadeStart = 25000\n"
"			fadeEnd = 50000\n"
"			deactivateAltitude = 180000\n"
"			mapMaxHeight = 20000\n"
"			materialType = AtmosphericTriplanarZoomRotation\n"
"			PhysicsMaterial\n"
"			{\n"
"				bounceCombine = Average\n"
"				frictionCombine = Maximum\n"
"				bounciness = 0\n"
"				staticFriction = 0.8\n"
"				dynamicFriction = 0.6\n"
"			}\n"
"			Material\n"
"			{\n"
"				factor = 3\n"
"				factorBlendWidth = 0.1\n"
"				factorRotation = 180\n"
"				saturation = 0\n"
"				contrast = 1.1\n"
"				tintColor = 1,1,1,0\n"
"				specularColor = 0.220588207,0.220588207,0.220588207,0.501960814\n"
"				albedoBrightness = 2\n"
"				steepPower = 2\n"
"				steepTexStart = 0\n"
"				steepTexEnd = 30000\n"
"				steepTex = BUILTIN/ikeSteep_diffuse\n"
"				steepTexScale = 1,1\n"
"				steepTexOffset = 0,0\n"
"				steepBumpMap = BUILTIN/ikeSteep_nrm\n"
"				steepBumpMapScale = 1,1\n"
"				steepBumpMapOffset = 0,0\n"
"				steepNearTiling = 50\n"
"				steepTiling = 50\n"
"				lowTexScale = 1,1\n"
"				lowTexOffset = 0,0\n"
"				lowTiling = 100000\n"
"				midTex = BUILTIN/ikeGround_diffuse\n"
"				midTexScale = 1,1\n"
"				midTexOffset = 0,0\n"
"				midTiling = 150000\n"
"				midBumpMap = BUILTIN/ikeGround_nrm\n"
"				midBumpMapScale = 1,1\n"
"				midBumpMapOffset = 0,0\n"
"				midBumpTiling = 150000\n"
"				highTexScale = 1,1\n"
"				highTexOffset = 0,0\n"
"				highTiling = 100000\n"
"				lowStart = 0\n"
"				lowEnd = 0\n"
"				highStart = 2\n"
"				highEnd = 2\n"
"				globalDensity = 1\n"
"				fogColorRampScale = 1,1\n"
"				fogColorRampOffset = 0,0\n"
"				planetOpacity = 0\n"
"				oceanFogDistance = 1000\n"
"			}\n"
"			FallbackMaterial\n"
"			{\n"
"				saturation = 1\n"
"				contrast = 1.2\n"
"				tintColor = 1,1,1,0\n"
"				texTiling = 1024\n"
"				texPower = 0.75\n"
"				multiPower = 0.75\n"
"				groundTexStart = 0\n"
"				groundTexEnd = 20000\n"
"				multiFactor = 0.5\n"
"				mainTex = BUILTIN/RockyGround\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				planetOpacity = 1\n"
"			}\n"
"			Mods\n"
"			{\n"
"				VertexSimplexHeightAbsolute\n"
"				{\n"
"					deformity = 12000\n"
"					frequency = 1\n"
"					octaves = 2\n"
"					persistence = 0.5\n"
"					seed = 2297\n"
"					order = 10\n"
"					enabled = True\n"
"					name = _Height\n"
"				}\n"
"				VertexHeightNoise\n"
"				{\n"
"					deformity = 1600\n"
"					frequency = 3\n"
"					octaves = 8\n"
"					persistence = 0.5\n"
"					seed = 8893284\n"
"					noiseType = RiggedMultifractal\n"
"					mode = Low\n"
"					lacunarity = 2.5\n"
"					order = 19\n"
"					enabled = True\n"
"					name = _Height\n"
"				}\n"
"				VertexSimplexHeight\n"
"				{\n"
"					deformity = 100\n"
"					frequency = 12\n"
"					octaves = 8\n"
"					persistence = 0.5\n"
"					seed = 56899452\n"
"					order = 20\n"
"					enabled = True\n"
"					name = _Height\n"
"				}\n"
"				AltitudeAlpha\n"
"				{\n"
"					atmosphereDepth = 8000\n"
"					invert = False\n"
"					order = 999999999\n"
"					enabled = True\n"
"					name = _Material_ModProjection\n"
"				}\n"
"				VertexSimplexNoiseColor\n"
"				{\n"
"					blend = 0.05\n"
"					colorStart = 0,0,0,0\n"
"					colorEnd = 0.791044772,0.791044772,0.791044772,0\n"
"					frequency = 2\n"
"					octaves = 2\n"
"					persistence = 0.5\n"
"					seed = 456364\n"
"					order = 100\n"
"					enabled = True\n"
"					name = _Color\n"
"				}\n"
"				VertexColorMap\n"
"				{\n"
"					map = BUILTIN/desertplanetmoon_coloroverlay\n"
"					order = 99\n"
"					enabled = True\n"
"					name = _Color\n"
"				}\n"
"				LandControl\n"
"				{\n"
"					altitudeBlend = 0\n"
"					altitudeFrequency = 1\n"
"					altitudeOctaves = 1\n"
"					altitudePersistance = 1\n"
"					altitudeSeed = 1\n"
"					createColors = False\n"
"					createScatter = True\n"
"					latitudeBlend = 0\n"
"					latitudeFrequency = 1\n"
"					latitudeOctaves = 1\n"
"					latitudePersistance = 1\n"
"					latitudeSeed = 1\n"
"					longitudeBlend = 0\n"
"					longitudeFrequency = 1\n"
"					longitudeOctaves = 1\n"
"					longitudePersistance = 1\n"
"					longitudeSeed = 1\n"
"					useHeightMap = False\n"
"					vHeightMax = 10000\n"
"					order = 999999\n"
"					enabled = True\n"
"					name = Scatter\n"
"					Scatters\n"
"					{\n"
"						Value\n"
"						{\n"
"							name = boulder\n"
"							materialType = KSPBumped\n"
"							material = BUILTIN/ikeScatter\n"
"							mesh = BUILTIN/boulder\n"
"							castShadows = True\n"
"							densityFactor = 1\n"
"							maxCache = 512\n"
"							maxCacheDelta = 32\n"
"							maxLevelOffset = 0\n"
"							maxScale = 2\n"
"							maxScatter = 20\n"
"							maxSpeed = 1000\n"
"							minScale = 0.1\n"
"							recieveShadows = True\n"
"							seed = 231123\n"
"							verticalOffset = 0\n"
"							instancing = False\n"
"							rotation = 0 360\n"
"							useBetterDensity = False\n"
"							spawnChance = 1\n"
"							ignoreDensityGameSetting = False\n"
"							densityVariance = -0.5 0.5\n"
"							delete = False\n"
"							Material\n"
"							{\n"
"								mainTex = BUILTIN/ikeScatterDiffuse\n"
"								mainTexScale = 1,1\n"
"								mainTexOffset = 0,0\n"
"								bumpMap = BUILTIN/ikeScatterNRM\n"
"								bumpMapScale = 1,1\n"
"								bumpMapOffset = 0,0\n"
"								color = 1,1,1,1\n"
"								opacity = 1\n"
"								rimFalloff = 0.1\n"
"								rimColor = 0,0,0,0\n"
"								temperatureColor = 0,0,0,0\n"
"								burnColor = 1,1,1,1\n"
"								underwaterFogFactor = 0\n"
"							}\n"
"						}\n"
"					}\n"
"					LandClasses\n"
"					{\n"
"						Value\n"
"						{\n"
"							alterApparentHeight = 0\n"
"							alterRealHeight = 0\n"
"							color = 0,0,0,0\n"
"							coverageBlend = 0\n"
"							coverageFrequency = 1\n"
"							coverageOctaves = 1\n"
"							coveragePersistance = 1\n"
"							coverageSeed = 1\n"
"							name = Base\n"
"							latDelta = 1\n"
"							latitudeDouble = False\n"
"							lonDelta = 1\n"
"							minimumRealHeight = 0\n"
"							noiseBlend = 0\n"
"							noiseColor = 0,0,0,0\n"
"							noiseFrequency = 1\n"
"							noiseOctaves = 1\n"
"							noisePersistance = 1\n"
"							noiseSeed = 1\n"
"							delete = False\n"
"							altitudeRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							latitudeDoubleRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							latitudeRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							longitudeRange\n"
"							{\n"
"								endEnd = 2\n"
"								endStart = 2\n"
"								startEnd = -1\n"
"								startStart = -1\n"
"							}\n"
"							Scatters\n"
"							{\n"
"								Value\n"
"								{\n"
"									density = 0.200000002980232\n"
"									scatterName = boulder\n"
"									delete = False\n"
"								}\n"
"							}\n"
"						}\n"
"					}\n"
"				}\n"
"				City\n"
"				{\n"
"					debugOrientated = False\n"
"					frameDelta = 1\n"
"					randomizeOnSphere = True\n"
"					reorientToSphere = True\n"
"					reorientFinalAngle = 45\n"
"					reorientInitialUp = 0,1,0\n"
"					repositionRadial = 513856,-290549,-122798\n"
"					repositionRadiusOffset = 2948.5\n"
"					repositionToSphere = True\n"
"					repositionToSphereSurface = True\n"
"					repositionToSphereSurfaceAddHeight = False\n"
"					commnetStation = False\n"
"					isKSC = False\n"
"					order = 100\n"
"					enabled = True\n"
"					name = Randolith\n"
"					LOD\n"
"					{\n"
"						Value\n"
"						{\n"
"							visibleRange = 10000\n"
"							scale = 0,0,0\n"
"							delete = False\n"
"						}\n"
"					}\n"
"				}\n"
"			}\n"
"		}\n"
"		Debug\n"
"		{\n"
"			exportMesh = True // Whether Kopernicus should save a .bin file with the ScaledSpace mesh.\n"
"			update = False // Setting this to true will force Kopernicus to update the ScaledSpace mesh.\n"
"			showSOI = False\n"
"		}\n"
"	}\n"
"}\n";
#endif