#ifndef MINMUS_H
#define MINMUS_H
char const *Minmus_cfg = "// KittopiaTech - a Kopernicus Visual Editor\n"
"\n"
"@Kopernicus:NEEDS[!Kopernicus]\n"
"{\n"
"	Body\n"
"	{\n"
"		name = Minmus\n"
"		barycenter = False\n"
"		identifier = Squad/Minmus\n"
"		implements = \n"
"		finalizeOrbit = False\n"
"		randomMainMenuBody = False\n"
"		contractWeight = 30\n"
"		Properties\n"
"		{\n"
"			description = Minmus is the smallest moon orbiting Kerbin. From the surface of Kerbin, it can be seen on clear days as a tiny blue speck in the sky. It is often mistaken as dirt on telescope lenses or dead pixels, but the top minds at the Kerbal Astronomical Society assure us it is a real moon nevertheless.\n"
"			radius = 60000\n"
"			geeASL = 0.05001708099188\n"
"			mass = 2.64575795662095E+19\n"
"			gravParameter = 1765800026.31247\n"
"			rotates = True\n"
"			rotationPeriod = 40400\n"
"			tidallyLocked = False\n"
"			initialRotation = 230\n"
"			inverseRotThresholdAltitude = 100000\n"
"			albedo = 0.5\n"
"			emissivity = 0.7\n"
"			coreTemperatureOffset = 1\n"
"			timewarpAltitudeLimits = 0 3000 3000 6000 12000 24000 48000 60000\n"
"			sphereOfInfluence = 2247428.3879023\n"
"			solarRotationPeriod = False\n"
"			navballSwitchRadiusMult = 0.06\n"
"			navballSwitchRadiusMultLow = 0.055\n"
"			biomeMap = BUILTIN/minmus_biome\n"
"			nonExactThreshold = -1\n"
"			exactSearch = False\n"
"			useTheInName = False\n"
"			displayName = Minmus^N\n"
"			selectable = True\n"
"			RnDVisibility = Visible\n"
"			RnDRotation = False\n"
"			maxZoom = 60000\n"
"			ScienceValues\n"
"			{\n"
"				landedDataValue = 5 // Science multiplier for landed science.\n"
"				splashedDataValue = 1 // Science multiplier for splashed down science.\n"
"				flyingLowDataValue = 1 // Science multiplier for flying low science.\n"
"				flyingHighDataValue = 1 // Science multiplier for flying high science.\n"
"				inSpaceLowDataValue = 4 // Science multiplier for in space low science.\n"
"				inSpaceHighDataValue = 2.5 // Science multiplier for in space high science.\n"
"				recoveryValue = 2.5\n"
"				flyingAltitudeThreshold = 18000 // Altitude when \"flying at <body>\" transitions from/to \"from <body>'s upper atmosphere\"\n"
"				spaceAltitudeThreshold = 30000 // Altitude when \"in space low\" transitions from/to \"in space high\"\n"
"			}\n"
"			Biomes\n"
"			{\n"
"				Value\n"
"				{\n"
"					name = Highlands // The name of this biome.\n"
"					displayName = Highlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.380392164,0.513725519,0.509803951,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Midlands // The name of this biome.\n"
"					displayName = Midlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.529411793,0.670588255,0.615686297,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Lowlands // The name of this biome.\n"
"					displayName = Lowlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.690196097,0.882352948,0.807843149,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Flats // The name of this biome.\n"
"					displayName = Flats // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.752941191,1,0.905882359,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Great Flats // The name of this biome.\n"
"					displayName = Great Flats // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.411764711,0.760784328,0.737254918,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Greater Flats // The name of this biome.\n"
"					displayName = Greater Flats // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.647058845,0.843137264,0.850980401,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Lesser Flats // The name of this biome.\n"
"					displayName = Lesser Flats // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.545098066,0.831372559,0.811764717,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Poles // The name of this biome.\n"
"					displayName = Poles // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 1,1,1,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Slopes // The name of this biome.\n"
"					displayName = Slopes // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.600000024,0.800000012,0.733333349,1 // The color of the biome on the biome map.\n"
"				}\n"
"			}\n"
"		}\n"
"		Orbit\n"
"		{\n"
"			referenceBody = Kerbin // The body that this body is orbiting around.\n"
"			inclination = 6\n"
"			eccentricity = 0\n"
"			semiMajorAxis = 47000000 // The altitude of the highest point in the orbit\n"
"			longitudeOfAscendingNode = 78 // The position of the highest point on the orbit circle\n"
"			argumentOfPeriapsis = 38\n"
"			meanAnomalyAtEpoch = 0.899999976158142\n"
"			meanAnomalyAtEpochD = 51.5662001957363\n"
"			epoch = 0\n"
"			color = 0.556862772,0.454901963,0.627451003,0.501960814 // The color of the orbit line in the Tracking Station\n"
"			nodeColor = 0.556862772,0.454901963,0.627451003,0.501960814 // The color of the circle that marks the planets current position on the orbit\n"
"			mode = REDRAW_AND_RECALCULATE\n"
"			icon = ALL\n"
"			cameraSmaRatioBounds = 0.12 12\n"
"			period = 1077310.52101881\n"
"		}\n"
"		ScaledVersion\n"
"		{\n"
"			type = Vacuum\n"
"			fadeStart = 95000\n"
"			fadeEnd = 140000\n"
"			sphericalModel = False\n"
"			deferMesh = False\n"
"			invisible = False\n"
"			Material\n"
"			{\n"
"				color = 0.735294104,0.735294104,0.735294104,1\n"
"				specColor = 0.191176474,0.191176474,0.191176474,1\n"
"				shininess = 0.03\n"
"				texture = BUILTIN/NewMunSurfaceMap00\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				normals = BUILTIN/NormalMap\n"
"				bumpMapScale = 1,1\n"
"				bumpMapOffset = 0,0\n"
"				opacity = 1\n"
"				resourceMapScale = 1,1\n"
"				resourceMapOffset = 0,0\n"
"			}\n"
"		}\n"
"		PQS\n"
"		{\n"
"			minLevel = 2\n"
"			maxLevel = 7\n"
"			minDetailDistance = 8\n"
"			maxQuadLengthsPerFrame = 0.03\n"
"			fadeStart = 100000\n"
"			fadeEnd = 145000\n"
"			deactivateAltitude = 180000\n"
"			mapMaxHeight = 4000\n"
"			materialType = AtmosphericTriplanarZoomRotation\n"
"			PhysicsMaterial\n"
"			{\n"
"				bounceCombine = Multiply\n"
"				frictionCombine = Maximum\n"
"				bounciness = 0\n"
"				staticFriction = 0.9\n"
"				dynamicFriction = 0.9\n"
"			}\n"
"			Material\n"
"			{\n"
"				factor = 14.26\n"
"				factorBlendWidth = 0.05\n"
"				factorRotation = 75\n"
"				saturation = 1.15\n"
"				contrast = 1\n"
"				tintColor = 1,1,1,0\n"
"				specularColor = 0.191176474,0.191176474,0.191176474,1\n"
"				albedoBrightness = 1.64\n"
"				steepPower = 1.5\n"
"				steepTexStart = 30000\n"
"				steepTexEnd = 60000\n"
"				steepTex = BUILTIN/MunCliff [Diffuse]\n"
"				steepTexScale = 1,1\n"
"				steepTexOffset = 0,0\n"
"				steepBumpMap = BUILTIN/MunCliff [Normal]\n"
"				steepBumpMapScale = 1,1\n"
"				steepBumpMapOffset = 0,0\n"
"				steepNearTiling = 500\n"
"				steepTiling = 350\n"
"				lowTexScale = 1,1\n"
"				lowTexOffset = 0,0\n"
"				lowTiling = 1\n"
"				midTex = BUILTIN/Minmus [Diffuse]\n"
"				midTexScale = 1,1\n"
"				midTexOffset = 0,0\n"
"				midTiling = 150000\n"
"				midBumpMap = BUILTIN/Minmus [Normal]\n"
"				midBumpMapScale = 1,1\n"
"				midBumpMapOffset = 0,0\n"
"				midBumpTiling = 150000\n"
"				highTexScale = 1,1\n"
"				highTexOffset = 0,0\n"
"				highTiling = 1.5\n"
"				lowStart = -1\n"
"				lowEnd = -1\n"
"				highStart = 1\n"
"				highEnd = 1\n"
"				globalDensity = 1\n"
"				fogColorRampScale = 1,1\n"
"				fogColorRampOffset = 0,0\n"
"				planetOpacity = 0\n"
"				oceanFogDistance = 1000\n"
"			}\n"
"			FallbackMaterial\n"
"			{\n"
"				saturation = 1\n"
"				contrast = 3\n"
"				tintColor = 1,1,1,0\n"
"				texTiling = 1024\n"
"				texPower = 0.75\n"
"				multiPower = 0.75\n"
"				groundTexStart = 0\n"
"				groundTexEnd = 5000\n"
"				multiFactor = 0.5\n"
"				mainTex = BUILTIN/terrain_sand00\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				planetOpacity = 0\n"
"			}\n"
"			Mods\n"
"			{\n"
"				AltitudeAlpha\n"
"				{\n"
"					atmosphereDepth = 8000\n"
"					invert = False\n"
"					order = 999999999\n"
"					enabled = True\n"
"					name = _Material_ModProjection\n"
"				}\n"
"				VertexPlanet\n"
"				{\n"
"					buildHeightColors = False\n"
"					colorDeformity = 6000\n"
"					deformity = 5000\n"
"					oceanDepth = 0\n"
"					oceanLevel = 0\n"
"					oceanSnap = False\n"
"					oceanStep = 0\n"
"					seed = 23123\n"
"					terrainRidgeBalance = 0.1\n"
"					terrainRidgesMax = 1\n"
"					terrainRidgesMin = 0.4\n"
"					terrainShapeEnd = -2\n"
"					terrainShapeStart = 2\n"
"					terrainSmoothing = 0.100000001490116\n"
"					order = 100\n"
"					enabled = True\n"
"					name = VertexPlanet\n"
"					ContinentalSimplex\n"
"					{\n"
"						deformity = 1\n"
"						frequency = 1\n"
"						octaves = 10\n"
"						persistance = 0.400000005960464\n"
"						seed = 0\n"
"					}\n"
"					RuggednessSimplex\n"
"					{\n"
"						deformity = 1\n"
"						frequency = 0.5\n"
"						octaves = 4\n"
"						persistance = 0.5\n"
"						seed = 0\n"
"					}\n"
"					SharpnessNoise\n"
"					{\n"
"						deformity = 0.00100000004749745\n"
"						frequency = 0.5\n"
"						octaves = 4\n"
"						persistance = 0.5\n"
"						seed = 0\n"
"					}\n"
"					SharpnessSimplexMap\n"
"					{\n"
"						deformity = 50\n"
"						frequency = 1.5\n"
"						octaves = 4\n"
"						persistance = 0.550000011920929\n"
"						seed = 0\n"
"					}\n"
"					LandClasses\n"
"					{\n"
"						Value\n"
"						{\n"
"							name = AbyPl\n"
"							baseColor = 0.450980395,0.588235319,0.533333361,1\n"
"							colorNoise = 0.4627451,0.749019623,0.635294139,1\n"
"							colorNoiseAmount = 0.200000002980232\n"
"							fractalEnd = 0.00100000004749745\n"
"							fractalStart = 0\n"
"							lerpToNext = True\n"
"							fractalDelta = 0.00100000004749745\n"
"							endHeight = 0\n"
"							startHeight = 0\n"
"							delete = False\n"
"							SimplexNoiseMap\n"
"							{\n"
"								deformity = 1\n"
"								frequency = 4\n"
"								octaves = 4\n"
"								persistance = 0.600000023841858\n"
"								seed = 0\n"
"							}\n"
"						}\n"
"						Value\n"
"						{\n"
"							name = Beach\n"
"							baseColor = 0.635294139,0.78039217,0.725490212,1\n"
"							colorNoise = 0.332423717,0.350746274,0.333064348,1\n"
"							colorNoiseAmount = 0.200000002980232\n"
"							fractalEnd = 0.449999988079071\n"
"							fractalStart = 0.00100000004749745\n"
"							lerpToNext = True\n"
"							fractalDelta = 0.448999988031574\n"
"							endHeight = 0\n"
"							startHeight = 0\n"
"							delete = False\n"
"							SimplexNoiseMap\n"
"							{\n"
"								deformity = 1\n"
"								frequency = 4\n"
"								octaves = 4\n"
"								persistance = 0.600000023841858\n"
"								seed = 0\n"
"							}\n"
"						}\n"
"						Value\n"
"						{\n"
"							name = Grass\n"
"							baseColor = 0.725490212,0.831372559,0.729411781,1\n"
"							colorNoise = 0.5,0.5,0.425373137,1\n"
"							colorNoiseAmount = 0.300000011920929\n"
"							fractalEnd = 0.899999976158142\n"
"							fractalStart = 0.449999988079071\n"
"							lerpToNext = True\n"
"							fractalDelta = 0.449999988079071\n"
"							endHeight = 0\n"
"							startHeight = 0\n"
"							delete = False\n"
"							SimplexNoiseMap\n"
"							{\n"
"								deformity = 1\n"
"								frequency = 3\n"
"								octaves = 4\n"
"								persistance = 0.600000023841858\n"
"								seed = 0\n"
"							}\n"
"						}\n"
"						Value\n"
"						{\n"
"							name = Snow\n"
"							baseColor = 0.431444645,0.514705896,0.450367659,0.686274529\n"
"							colorNoise = 0.430215567,0.432835817,0.339162409,1\n"
"							colorNoiseAmount = 0.400000005960464\n"
"							fractalEnd = 2\n"
"							fractalStart = 0.899999976158142\n"
"							lerpToNext = False\n"
"							fractalDelta = 1.10000002384186\n"
"							endHeight = 0\n"
"							startHeight = 0\n"
"							delete = False\n"
"							SimplexNoiseMap\n"
"							{\n"
"								deformity = 1\n"
"								frequency = 2\n"
"								octaves = 4\n"
"								persistance = 0.600000023841858\n"
"								seed = 0\n"
"							}\n"
"						}\n"
"					}\n"
"					TerrainTypeSimplex\n"
"					{\n"
"						deformity = 1\n"
"						frequency = 4\n"
"						octaves = 12\n"
"						persistance = 0.7\n"
"						seed = 0\n"
"					}\n"
"				}\n"
"				LandControl\n"
"				{\n"
"					altitudeBlend = 0\n"
"					altitudeFrequency = 1\n"
"					altitudeOctaves = 1\n"
"					altitudePersistance = 1\n"
"					altitudeSeed = 1\n"
"					createColors = False\n"
"					createScatter = True\n"
"					latitudeBlend = 0\n"
"					latitudeFrequency = 1\n"
"					latitudeOctaves = 1\n"
"					latitudePersistance = 1\n"
"					latitudeSeed = 1\n"
"					longitudeBlend = 0\n"
"					longitudeFrequency = 1\n"
"					longitudeOctaves = 1\n"
"					longitudePersistance = 1\n"
"					longitudeSeed = 1\n"
"					useHeightMap = False\n"
"					vHeightMax = 10000\n"
"					order = 999999\n"
"					enabled = True\n"
"					name = Scatter\n"
"					Scatters\n"
"					{\n"
"						Value\n"
"						{\n"
"							name = IceBoulder\n"
"							materialType = KSPBumpedSpecular\n"
"							material = BUILTIN/scatter_rock_minmusIce\n"
"							mesh = BUILTIN/boulder\n"
"							castShadows = True\n"
"							densityFactor = 1\n"
"							maxCache = 512\n"
"							maxCacheDelta = 32\n"
"							maxLevelOffset = 0\n"
"							maxScale = 3\n"
"							maxScatter = 20\n"
"							maxSpeed = 1000\n"
"							minScale = 0.5\n"
"							recieveShadows = True\n"
"							seed = 231122\n"
"							verticalOffset = 0\n"
"							instancing = False\n"
"							rotation = 0 360\n"
"							useBetterDensity = False\n"
"							spawnChance = 1\n"
"							ignoreDensityGameSetting = False\n"
"							densityVariance = -0.5 0.5\n"
"							delete = False\n"
"							Material\n"
"							{\n"
"								mainTex = BUILTIN/MinmusIceBoulder [Diffuse]\n"
"								mainTexScale = 1,1\n"
"								mainTexOffset = 0,0\n"
"								bumpMap = BUILTIN/MinmusBoulder [Diffuse]\n"
"								bumpMapScale = 1,1\n"
"								bumpMapOffset = 0,0\n"
"								color = 0.65882355,0.788235307,0.729411781,0.686274529\n"
"								specColor = 0.0882353187,0.0882353187,0.0882353187,1\n"
"								shininess = 0.078125\n"
"								opacity = 1\n"
"								rimFalloff = 0.1\n"
"								rimColor = 0,0,0,0\n"
"								temperatureColor = 0,0,0,0\n"
"								burnColor = 1,1,1,1\n"
"								underwaterFogFactor = 0\n"
"							}\n"
"						}\n"
"						Value\n"
"						{\n"
"							name = SnowBoulder\n"
"							materialType = KSPBumpedSpecular\n"
"							material = BUILTIN/scatter_rock_minmusSnow\n"
"							mesh = BUILTIN/boulder\n"
"							castShadows = True\n"
"							densityFactor = 1\n"
"							maxCache = 512\n"
"							maxCacheDelta = 32\n"
"							maxLevelOffset = 0\n"
"							maxScale = 3\n"
"							maxScatter = 20\n"
"							maxSpeed = 1000\n"
"							minScale = 0.5\n"
"							recieveShadows = True\n"
"							seed = 231123\n"
"							verticalOffset = 0\n"
"							instancing = False\n"
"							rotation = 0 360\n"
"							useBetterDensity = False\n"
"							spawnChance = 1\n"
"							ignoreDensityGameSetting = False\n"
"							densityVariance = -0.5 0.5\n"
"							delete = False\n"
"							Material\n"
"							{\n"
"								mainTex = BUILTIN/MinmusSnowBoulder [Diffuse]\n"
"								mainTexScale = 1,1\n"
"								mainTexOffset = 0,0\n"
"								bumpMap = BUILTIN/MinmusBoulder [Diffuse]\n"
"								bumpMapScale = 1,1\n"
"								bumpMapOffset = 0,0\n"
"								color = 0.544009507,0.632352948,0.562896669,0.686274529\n"
"								specColor = 0.0882353187,0.0882353187,0.0882353187,1\n"
"								shininess = 0.078125\n"
"								opacity = 1\n"
"								rimFalloff = 0.1\n"
"								rimColor = 0,0,0,0\n"
"								temperatureColor = 0,0,0,0\n"
"								burnColor = 1,1,1,1\n"
"								underwaterFogFactor = 0\n"
"							}\n"
"						}\n"
"					}\n"
"					LandClasses\n"
"					{\n"
"						Value\n"
"						{\n"
"							alterApparentHeight = 0\n"
"							alterRealHeight = 0\n"
"							color = 0,0,0,0\n"
"							coverageBlend = 0\n"
"							coverageFrequency = 1\n"
"							coverageOctaves = 1\n"
"							coveragePersistance = 1\n"
"							coverageSeed = 1\n"
"							name = Ice\n"
"							latDelta = 1\n"
"							latitudeDouble = False\n"
"							lonDelta = 1\n"
"							minimumRealHeight = 0\n"
"							noiseBlend = 0\n"
"							noiseColor = 0,0,0,0\n"
"							noiseFrequency = 1\n"
"							noiseOctaves = 1\n"
"							noisePersistance = 1\n"
"							noiseSeed = 1\n"
"							delete = False\n"
"							altitudeRange\n"
"							{\n"
"								endEnd = 0.005\n"
"								endStart = 0.005\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							latitudeDoubleRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							latitudeRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							longitudeRange\n"
"							{\n"
"								endEnd = 2\n"
"								endStart = 2\n"
"								startEnd = -1\n"
"								startStart = -1\n"
"							}\n"
"							Scatters\n"
"							{\n"
"								Value\n"
"								{\n"
"									density = 1\n"
"									scatterName = IceBoulder\n"
"									delete = False\n"
"								}\n"
"							}\n"
"						}\n"
"						Value\n"
"						{\n"
"							alterApparentHeight = 0\n"
"							alterRealHeight = 0\n"
"							color = 0,0,0,0\n"
"							coverageBlend = 0\n"
"							coverageFrequency = 1\n"
"							coverageOctaves = 1\n"
"							coveragePersistance = 1\n"
"							coverageSeed = 1\n"
"							name = Snow\n"
"							latDelta = 1\n"
"							latitudeDouble = False\n"
"							lonDelta = 1\n"
"							minimumRealHeight = 0\n"
"							noiseBlend = 0\n"
"							noiseColor = 0,0,0,0\n"
"							noiseFrequency = 1\n"
"							noiseOctaves = 1\n"
"							noisePersistance = 1\n"
"							noiseSeed = 1\n"
"							delete = False\n"
"							altitudeRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0.08\n"
"								startStart = 0.08\n"
"							}\n"
"							latitudeDoubleRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							latitudeRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							longitudeRange\n"
"							{\n"
"								endEnd = 2\n"
"								endStart = 2\n"
"								startEnd = -1\n"
"								startStart = -1\n"
"							}\n"
"							Scatters\n"
"							{\n"
"								Value\n"
"								{\n"
"									density = 1\n"
"									scatterName = SnowBoulder\n"
"									delete = False\n"
"								}\n"
"							}\n"
"						}\n"
"					}\n"
"				}\n"
"				City\n"
"				{\n"
"					debugOrientated = False\n"
"					frameDelta = 1\n"
"					randomizeOnSphere = False\n"
"					reorientToSphere = True\n"
"					reorientFinalAngle = 67.65\n"
"					reorientInitialUp = 0,1,0\n"
"					repositionRadial = 1666,1470,2891\n"
"					repositionRadiusOffset = -1\n"
"					repositionToSphere = True\n"
"					repositionToSphereSurface = True\n"
"					repositionToSphereSurfaceAddHeight = True\n"
"					commnetStation = False\n"
"					isKSC = False\n"
"					order = 100\n"
"					enabled = True\n"
"					name = Monolith00\n"
"					LOD\n"
"					{\n"
"						Value\n"
"						{\n"
"							visibleRange = 10000\n"
"							scale = 0,0,0\n"
"							delete = False\n"
"						}\n"
"					}\n"
"				}\n"
"				City\n"
"				{\n"
"					debugOrientated = False\n"
"					frameDelta = 1\n"
"					randomizeOnSphere = True\n"
"					reorientToSphere = True\n"
"					reorientFinalAngle = 45\n"
"					reorientInitialUp = 0,1,0\n"
"					repositionRadial = 513856,-290549,-122798\n"
"					repositionRadiusOffset = 2948.5\n"
"					repositionToSphere = True\n"
"					repositionToSphereSurface = True\n"
"					repositionToSphereSurfaceAddHeight = False\n"
"					commnetStation = False\n"
"					isKSC = False\n"
"					order = 100\n"
"					enabled = True\n"
"					name = Randolith\n"
"					LOD\n"
"					{\n"
"						Value\n"
"						{\n"
"							visibleRange = 10000\n"
"							scale = 0,0,0\n"
"							delete = False\n"
"						}\n"
"					}\n"
"				}\n"
"			}\n"
"		}\n"
"		Debug\n"
"		{\n"
"			exportMesh = True // Whether Kopernicus should save a .bin file with the ScaledSpace mesh.\n"
"			update = False // Setting this to true will force Kopernicus to update the ScaledSpace mesh.\n"
"			showSOI = False\n"
"		}\n"
"	}\n"
"}\n";
#endif