#include <string>
#ifndef MOHO_H
#define MOHO_H
std::string Moho_cfg = "// KittopiaTech - a Kopernicus Visual Editor\n"
"\n"
"@Kopernicus:NEEDS[!Kopernicus]\n"
"{\n"
"	Body\n"
"	{\n"
"		name = Moho\n"
"		barycenter = False\n"
"		identifier = Squad/Moho\n"
"		implements = \n"
"		finalizeOrbit = False\n"
"		randomMainMenuBody = False\n"
"		contractWeight = 30\n"
"		Properties\n"
"		{\n"
"			description = Moho figures in Kerbal mythology as a fiery place with oceans of flowing lava. In reality however, it’s much less interesting. Scientists speculate about possible ways to make it “awesome like in the stories”. Some of those ideas have led to new breakthroughs in aerospace technology.\n"
"			radius = 250000\n"
"			geeASL = 0.275093947318621\n"
"			mass = 2.52633139930162E+21\n"
"			gravParameter = 168609378654.509\n"
"			rotates = True\n"
"			rotationPeriod = 1210000\n"
"			tidallyLocked = False\n"
"			initialRotation = 190\n"
"			inverseRotThresholdAltitude = 100000\n"
"			albedo = 0.1\n"
"			emissivity = 0.9\n"
"			coreTemperatureOffset = 0\n"
"			timewarpAltitudeLimits = 0 10000 10000 30000 50000 100000 200000 300000\n"
"			sphereOfInfluence = 9646663.02332811\n"
"			solarRotationPeriod = False\n"
"			navballSwitchRadiusMult = 0.06\n"
"			navballSwitchRadiusMultLow = 0.055\n"
"			biomeMap = BUILTIN/moho_biome\n"
"			nonExactThreshold = -1\n"
"			exactSearch = False\n"
"			useTheInName = False\n"
"			displayName = Moho^N\n"
"			selectable = True\n"
"			RnDVisibility = Visible\n"
"			RnDRotation = False\n"
"			maxZoom = 60000\n"
"			ScienceValues\n"
"			{\n"
"				landedDataValue = 10 // Science multiplier for landed science.\n"
"				splashedDataValue = 1 // Science multiplier for splashed down science.\n"
"				flyingLowDataValue = 1 // Science multiplier for flying low science.\n"
"				flyingHighDataValue = 1 // Science multiplier for flying high science.\n"
"				inSpaceLowDataValue = 8 // Science multiplier for in space low science.\n"
"				inSpaceHighDataValue = 7 // Science multiplier for in space high science.\n"
"				recoveryValue = 7\n"
"				flyingAltitudeThreshold = 18000 // Altitude when \"flying at <body>\" transitions from/to \"from <body>'s upper atmosphere\"\n"
"				spaceAltitudeThreshold = 80000 // Altitude when \"in space low\" transitions from/to \"in space high\"\n"
"			}\n"
"			Biomes\n"
"			{\n"
"				Value\n"
"				{\n"
"					name = North Pole // The name of this biome.\n"
"					displayName = North Pole // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.839215696,0.741176486,0.650980413,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Northern Sinkhole Ridge // The name of this biome.\n"
"					displayName = Northern Sinkhole Ridge // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.650980413,0.501960814,0.368627459,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Northern Sinkhole // The name of this biome.\n"
"					displayName = Northern Sinkhole // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.4627451,0.419607848,0.384313732,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Midlands // The name of this biome.\n"
"					displayName = Midlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.70588237,0.56078434,0.427450985,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Western Lowlands // The name of this biome.\n"
"					displayName = Western Lowlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.345098048,0.294117659,0.254901975,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Central Lowlands // The name of this biome.\n"
"					displayName = Central Lowlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.345098048,0.309803933,0.282352954,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Highlands // The name of this biome.\n"
"					displayName = Highlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.776470602,0.623529434,0.486274511,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Minor Craters // The name of this biome.\n"
"					displayName = Minor Craters // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.301960796,0.266666681,0.239215687,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = South Western Lowlands // The name of this biome.\n"
"					displayName = South Western Lowlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.388235301,0.345098048,0.309803933,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = South Eastern Lowlands // The name of this biome.\n"
"					displayName = South Eastern Lowlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.419607848,0.376470596,0.337254912,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Canyon // The name of this biome.\n"
"					displayName = Canyon // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.294117659,0.243137255,0.203921571,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = South Pole // The name of this biome.\n"
"					displayName = South Pole // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.847058833,0.698039234,0.564705908,1 // The color of the biome on the biome map.\n"
"				}\n"
"			}\n"
"		}\n"
"		Orbit\n"
"		{\n"
"			referenceBody = Sun // The body that this body is orbiting around.\n"
"			inclination = 7\n"
"			eccentricity = 0.200000002980232\n"
"			semiMajorAxis = 5263138304 // The altitude of the highest point in the orbit\n"
"			longitudeOfAscendingNode = 70 // The position of the highest point on the orbit circle\n"
"			argumentOfPeriapsis = 15\n"
"			meanAnomalyAtEpoch = 3.14000010490417\n"
"			meanAnomalyAtEpochD = 179.908753681645\n"
"			epoch = 0\n"
"			color = 0.933333337,0.713725507,0.533333361,0.501960814 // The color of the orbit line in the Tracking Station\n"
"			nodeColor = 0.933333337,0.713725507,0.533333361,0.501960814 // The color of the circle that marks the planets current position on the orbit\n"
"			mode = REDRAW_AND_RECALCULATE\n"
"			icon = ALL\n"
"			cameraSmaRatioBounds = 0.03 25\n"
"			period = 2215754.21968432\n"
"		}\n"
"		ScaledVersion\n"
"		{\n"
"			type = Vacuum\n"
"			fadeStart = 30000\n"
"			fadeEnd = 40000\n"
"			sphericalModel = False\n"
"			deferMesh = False\n"
"			invisible = False\n"
"			Material\n"
"			{\n"
"				color = 1,1,1,1\n"
"				specColor = 0.0769999996,0.0769999996,0.0769999996,1\n"
"				shininess = 0.03\n"
"				texture = BUILTIN/moho01\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				normals = BUILTIN/moho02\n"
"				bumpMapScale = 1,1\n"
"				bumpMapOffset = 0,0\n"
"				opacity = 1\n"
"				resourceMapScale = 1,1\n"
"				resourceMapOffset = 0,0\n"
"			}\n"
"		}\n"
"		PQS\n"
"		{\n"
"			minLevel = 2\n"
"			maxLevel = 9\n"
"			minDetailDistance = 8\n"
"			maxQuadLengthsPerFrame = 0.03\n"
"			fadeStart = 45000\n"
"			fadeEnd = 150000\n"
"			deactivateAltitude = 150000\n"
"			mapMaxHeight = 8000\n"
"			materialType = AtmosphericTriplanarZoomRotation\n"
"			PhysicsMaterial\n"
"			{\n"
"				bounceCombine = Multiply\n"
"				frictionCombine = Maximum\n"
"				bounciness = 0\n"
"				staticFriction = 0.9\n"
"				dynamicFriction = 0.9\n"
"			}\n"
"			Material\n"
"			{\n"
"				factor = 7.73\n"
"				factorBlendWidth = 0.1\n"
"				factorRotation = 15\n"
"				saturation = 1\n"
"				contrast = 1\n"
"				tintColor = 1,1,1,0\n"
"				specularColor = 0.0754716992,0.0754716992,0.0754716992,0.200000003\n"
"				albedoBrightness = 1\n"
"				steepPower = 1\n"
"				steepTexStart = 0\n"
"				steepTexEnd = 200000\n"
"				steepTex = BUILTIN/MohoSteep\n"
"				steepTexScale = 1,1\n"
"				steepTexOffset = 0,0\n"
"				steepBumpMap = BUILTIN/MohoSteep_nrm\n"
"				steepBumpMapScale = 1,1\n"
"				steepBumpMapOffset = 0,0\n"
"				steepNearTiling = 2000\n"
"				steepTiling = 20\n"
"				lowTex = BUILTIN/MohoLow\n"
"				lowTexScale = 1,1\n"
"				lowTexOffset = 0,0\n"
"				lowTiling = 100000\n"
"				midTex = BUILTIN/MohoMid\n"
"				midTexScale = 1,1\n"
"				midTexOffset = 0,0\n"
"				midTiling = 100000\n"
"				midBumpMap = BUILTIN/MohoMid_nrm\n"
"				midBumpMapScale = 1,1\n"
"				midBumpMapOffset = 0,0\n"
"				midBumpTiling = 100000\n"
"				highTex = BUILTIN/MohoMid\n"
"				highTexScale = 1,1\n"
"				highTexOffset = 0,0\n"
"				highTiling = 100000\n"
"				lowStart = 0\n"
"				lowEnd = 0.3\n"
"				highStart = 1\n"
"				highEnd = 1\n"
"				globalDensity = 1\n"
"				fogColorRampScale = 1,1\n"
"				fogColorRampOffset = 0,0\n"
"				planetOpacity = 0\n"
"				oceanFogDistance = 1000\n"
"			}\n"
"			FallbackMaterial\n"
"			{\n"
"				saturation = 1.62\n"
"				contrast = 1.9\n"
"				tintColor = 1,1,1,0\n"
"				texTiling = 1024\n"
"				texPower = 0.75\n"
"				multiPower = 0.75\n"
"				groundTexStart = 0\n"
"				groundTexEnd = 20000\n"
"				multiFactor = 0.5\n"
"				mainTex = BUILTIN/RockyGround\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				planetOpacity = 1\n"
"			}\n"
"			Mods\n"
"			{\n"
"				VertexSimplexNoiseColor\n"
"				{\n"
"					blend = 1\n"
"					colorStart = 0.723880589,0.723880589,0.723880589,1\n"
"					colorEnd = 0,0,0,1\n"
"					frequency = 2\n"
"					octaves = 12\n"
"					persistence = 0.5\n"
"					seed = 346434\n"
"					order = 200\n"
"					enabled = True\n"
"					name = _Color\n"
"				}\n"
"				HeightColorMap\n"
"				{\n"
"					blend = 0.75\n"
"					order = 201\n"
"					enabled = True\n"
"					name = _Color\n"
"					LandClasses\n"
"					{\n"
"						Value\n"
"						{\n"
"							name = AbyPl\n"
"							color = 0,0,0,1\n"
"							altitudeStart = 0\n"
"							altitudeEnd = 0.400000005960464\n"
"							lerpToNext = True\n"
"							delete = False\n"
"						}\n"
"						Value\n"
"						{\n"
"							name = Beach\n"
"							color = 0.328358233,0.255016565,0.205510929,1\n"
"							altitudeStart = 0.400000005960464\n"
"							altitudeEnd = 1\n"
"							lerpToNext = False\n"
"							delete = False\n"
"						}\n"
"					}\n"
"				}\n"
"				AltitudeAlpha\n"
"				{\n"
"					atmosphereDepth = 7000\n"
"					invert = False\n"
"					order = 999999999\n"
"					enabled = True\n"
"					name = _Material_ModProjection\n"
"				}\n"
"				AerialPerspectiveMaterial\n"
"				{\n"
"					atmosphereDepth = 150000\n"
"					DEBUG_SetEveryFrame = True\n"
"					globalDensity = -1E-05\n"
"					heightFalloff = 6.75\n"
"					oceanDepth = 0\n"
"					order = 100\n"
"					enabled = True\n"
"					name = _Material_AerialPerspective\n"
"				}\n"
"				VertexHeightMap\n"
"				{\n"
"					map = BUILTIN/moho_height\n"
"					offset = 0\n"
"					deformity = 5000\n"
"					scaleDeformityByRadius = False\n"
"					order = 20\n"
"					enabled = True\n"
"					name = _HeightNoise\n"
"				}\n"
"				VertexSimplexHeight\n"
"				{\n"
"					deformity = 500\n"
"					frequency = 6\n"
"					octaves = 12\n"
"					persistence = 0.5\n"
"					seed = 456574\n"
"					order = 21\n"
"					enabled = True\n"
"					name = _HeightNoise\n"
"				}\n"
"				FlattenOcean\n"
"				{\n"
"					oceanRadius = 1\n"
"					order = 22\n"
"					enabled = True\n"
"					name = _HeightNoise\n"
"				}\n"
"				VertexHeightNoiseVertHeightCurve2\n"
"				{\n"
"					deformity = 2500\n"
"					ridgedAddFrequency = 32\n"
"					ridgedAddLacunarity = 2\n"
"					ridgedAddOctaves = 4\n"
"					ridgedAddSeed = 1212\n"
"					ridgedMode = Low\n"
"					ridgedSubFrequency = 32\n"
"					ridgedSubLacunarity = 2\n"
"					ridgedSubOctaves = 4\n"
"					ridgedSubSeed = 453123\n"
"					simplexFrequency = 24\n"
"					simplexHeightEnd = 5500\n"
"					simplexHeightStart = 10\n"
"					simplexOctaves = 4\n"
"					simplexPersistence = 0.5\n"
"					simplexSeed = 453452378\n"
"					order = 23\n"
"					enabled = True\n"
"					name = _HeightNoise\n"
"					simplexCurve\n"
"					{\n"
"						key = 0 0 0 0\n"
"						key = 0.6311918 0.4490898 1.432598 1.432598\n"
"						key = 1 1 0 0\n"
"					}\n"
"				}\n"
"				VertexSimplexHeightAbsolute\n"
"				{\n"
"					deformity = 200\n"
"					frequency = 18\n"
"					octaves = 7\n"
"					persistence = 0.5\n"
"					seed = 435345\n"
"					order = 30\n"
"					enabled = True\n"
"					name = _FineDetail\n"
"				}\n"
"				City\n"
"				{\n"
"					debugOrientated = False\n"
"					frameDelta = 1\n"
"					randomizeOnSphere = True\n"
"					reorientToSphere = True\n"
"					reorientFinalAngle = 45\n"
"					reorientInitialUp = 0,1,0\n"
"					repositionRadial = 513856,-290549,-122798\n"
"					repositionRadiusOffset = 2948.5\n"
"					repositionToSphere = True\n"
"					repositionToSphereSurface = True\n"
"					repositionToSphereSurfaceAddHeight = False\n"
"					commnetStation = False\n"
"					isKSC = False\n"
"					order = 100\n"
"					enabled = True\n"
"					name = Randolith\n"
"					LOD\n"
"					{\n"
"						Value\n"
"						{\n"
"							visibleRange = 10000\n"
"							scale = 0,0,0\n"
"							delete = False\n"
"						}\n"
"					}\n"
"				}\n"
"				City2\n"
"				{\n"
"					snapToSurface = True\n"
"					alt = 192.09375\n"
"					lat = 90\n"
"					lon = -4.78341462454E-06\n"
"					objectName = Mohole\n"
"					up = 0,1,0\n"
"					rotation = 0\n"
"					snapHeightOffset = 0\n"
"					commnetStation = False\n"
"					isKSC = False\n"
"					order = 100\n"
"					enabled = True\n"
"					name = Mohole\n"
"				}\n"
"			}\n"
"		}\n"
"		Debug\n"
"		{\n"
"			exportMesh = True // Whether Kopernicus should save a .bin file with the ScaledSpace mesh.\n"
"			update = False // Setting this to true will force Kopernicus to update the ScaledSpace mesh.\n"
"			showSOI = False\n"
"		}\n"
"	}\n"
"}\n";
#endif