#ifndef POL_H
#define POL_H
char const *Pol_cfg = "// KittopiaTech - a Kopernicus Visual Editor\n"
"\n"
"@Kopernicus:NEEDS[!Kopernicus]\n"
"{\n"
"	Body\n"
"	{\n"
"		name = Pol\n"
"		barycenter = False\n"
"		identifier = Squad/Pol\n"
"		implements = \n"
"		finalizeOrbit = False\n"
"		randomMainMenuBody = False\n"
"		contractWeight = 30\n"
"		Properties\n"
"		{\n"
"			description = This moon was especially hard to spot, as it looks just like a pollen grain, particularly when observed through telescopes based near dusty fields.Pol was finally discovered when someone decided to write down the location of the pollen, after having given up on yet another failed attempt to be rid of the smudge.\n"
"			radius = 44000\n"
"			geeASL = 0.0380129809873912\n"
"			mass = 1.08135065806823E+19\n"
"			gravParameter = 721702080\n"
"			rotates = True\n"
"			rotationPeriod = 901902.623531173\n"
"			tidallyLocked = True\n"
"			initialRotation = 25\n"
"			inverseRotThresholdAltitude = 100000\n"
"			albedo = 0.5\n"
"			emissivity = 0.5\n"
"			coreTemperatureOffset = 7\n"
"			timewarpAltitudeLimits = 0 5000 5000 5000 8000 12000 30000 90000\n"
"			sphereOfInfluence = 1042138.89230178\n"
"			solarRotationPeriod = False\n"
"			navballSwitchRadiusMult = 0.06\n"
"			navballSwitchRadiusMultLow = 0.055\n"
"			biomeMap = BUILTIN/pol_biome\n"
"			nonExactThreshold = -1\n"
"			exactSearch = False\n"
"			useTheInName = False\n"
"			displayName = Pol^N\n"
"			selectable = True\n"
"			RnDVisibility = Visible\n"
"			RnDRotation = False\n"
"			maxZoom = 60000\n"
"			ScienceValues\n"
"			{\n"
"				landedDataValue = 12 // Science multiplier for landed science.\n"
"				splashedDataValue = 1 // Science multiplier for splashed down science.\n"
"				flyingLowDataValue = 1 // Science multiplier for flying low science.\n"
"				flyingHighDataValue = 1 // Science multiplier for flying high science.\n"
"				inSpaceLowDataValue = 9 // Science multiplier for in space low science.\n"
"				inSpaceHighDataValue = 8 // Science multiplier for in space high science.\n"
"				recoveryValue = 8\n"
"				flyingAltitudeThreshold = 18000 // Altitude when \"flying at <body>\" transitions from/to \"from <body>'s upper atmosphere\"\n"
"				spaceAltitudeThreshold = 22000 // Altitude when \"in space low\" transitions from/to \"in space high\"\n"
"			}\n"
"			Biomes\n"
"			{\n"
"				Value\n"
"				{\n"
"					name = Poles // The name of this biome.\n"
"					displayName = Poles // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 1,0.952941179,0.772549033,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Lowlands // The name of this biome.\n"
"					displayName = Lowlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.713725507,0.647058845,0.407843143,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Highlands // The name of this biome.\n"
"					displayName = Highlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.960784316,0.894117653,0.639215708,1 // The color of the biome on the biome map.\n"
"				}\n"
"				Value\n"
"				{\n"
"					name = Midlands // The name of this biome.\n"
"					displayName = Midlands // The displayed name of the biome. Can be a localization tag.\n"
"					value = 0 // A value that gets multiplied with every amount of science that is returned in the biome.\n"
"					color = 0.831372559,0.75686276,0.478431374,1 // The color of the biome on the biome map.\n"
"				}\n"
"			}\n"
"		}\n"
"		Orbit\n"
"		{\n"
"			referenceBody = Jool // The body that this body is orbiting around.\n"
"			inclination = 4.25\n"
"			eccentricity = 0.17085\n"
"			semiMajorAxis = 179890000 // The altitude of the highest point in the orbit\n"
"			longitudeOfAscendingNode = 2 // The position of the highest point on the orbit circle\n"
"			argumentOfPeriapsis = 15\n"
"			meanAnomalyAtEpoch = 0.899999976158142\n"
"			meanAnomalyAtEpochD = 51.5662001957363\n"
"			epoch = 0\n"
"			color = 0.862745106,0.894117653,0.674509823,0.501960814 // The color of the orbit line in the Tracking Station\n"
"			nodeColor = 0.862745106,0.894117653,0.674509823,0.501960814 // The color of the circle that marks the planets current position on the orbit\n"
"			mode = REDRAW_AND_RECALCULATE\n"
"			icon = ALL\n"
"			cameraSmaRatioBounds = 0.12 12\n"
"			period = 901902.623531173\n"
"		}\n"
"		ScaledVersion\n"
"		{\n"
"			type = Vacuum\n"
"			fadeStart = 130000\n"
"			fadeEnd = 135000\n"
"			sphericalModel = False\n"
"			deferMesh = False\n"
"			invisible = False\n"
"			Material\n"
"			{\n"
"				color = 1,1,1,1\n"
"				specColor = 0,0,0,1\n"
"				shininess = 0.078125\n"
"				texture = BUILTIN/gp1minormoon200\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				normals = BUILTIN/gp1minormoon201\n"
"				bumpMapScale = 1,1\n"
"				bumpMapOffset = 0,0\n"
"				opacity = 1\n"
"				resourceMapScale = 1,1\n"
"				resourceMapOffset = 0,0\n"
"			}\n"
"		}\n"
"		PQS\n"
"		{\n"
"			minLevel = 2\n"
"			maxLevel = 9\n"
"			minDetailDistance = 8\n"
"			maxQuadLengthsPerFrame = 0.03\n"
"			fadeStart = 135000\n"
"			fadeEnd = 140000\n"
"			deactivateAltitude = 180000\n"
"			mapMaxHeight = 6000\n"
"			materialType = Vacuum\n"
"			PhysicsMaterial\n"
"			{\n"
"				bounceCombine = Average\n"
"				frictionCombine = Maximum\n"
"				bounciness = 0\n"
"				staticFriction = 0.8\n"
"				dynamicFriction = 0.6\n"
"			}\n"
"			Material\n"
"			{\n"
"				saturation = 1\n"
"				contrast = 1.2\n"
"				tintColor = 1,1,1,0\n"
"				texTiling = 700\n"
"				texPower = 0.75\n"
"				multiPower = 0.75\n"
"				groundTexStart = 0\n"
"				groundTexEnd = 20000\n"
"				steepTiling = 10\n"
"				steepPower = 0.25\n"
"				steepTexStart = 200000\n"
"				steepTexEnd = 300000\n"
"				deepTex = BUILTIN/RockyGround\n"
"				deepTexScale = 1,1\n"
"				deepTexOffset = 0,0\n"
"				deepMultiTex = BUILTIN/distantground\n"
"				deepMultiTexScale = 1,1\n"
"				deepMultiTexOffset = 0,0\n"
"				deepMultiFactor = 3\n"
"				mainTex = BUILTIN/RockyGround\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				mainMultiTex = BUILTIN/distantground\n"
"				mainMultiTexScale = 1,1\n"
"				mainMultiTexOffset = 0,0\n"
"				mainMultiFactor = 6\n"
"				highTex = BUILTIN/RockyGround\n"
"				highTexScale = 1,1\n"
"				highTexOffset = 0,0\n"
"				highMultiTex = BUILTIN/distantground\n"
"				highMultiTexScale = 1,1\n"
"				highMultiTexOffset = 0,0\n"
"				highMultiFactor = 12\n"
"				snowTex = BUILTIN/RockyGround\n"
"				snowTexScale = 1,1\n"
"				snowTexOffset = 0,0\n"
"				snowMultiTex = BUILTIN/distantground\n"
"				snowMultiTexScale = 1,1\n"
"				snowMultiTexOffset = 0,0\n"
"				snowMultiFactor = 14\n"
"				steepTex = BUILTIN/terrain_rock00\n"
"				steepTexScale = 1,1\n"
"				steepTexOffset = 0,0\n"
"				deepStart = 0\n"
"				deepEnd = 0.01\n"
"				mainLoStart = 0\n"
"				mainLoEnd = 0.05\n"
"				mainHiStart = 0.1\n"
"				mainHiEnd = 0.15\n"
"				hiLoStart = 0.1\n"
"				hiLoEnd = 0.15\n"
"				hiHiStart = 0.2\n"
"				hiHiEnd = 0.25\n"
"				snowStart = 0.2\n"
"				snowEnd = 0.25\n"
"				planetOpacity = 0\n"
"			}\n"
"			FallbackMaterial\n"
"			{\n"
"				saturation = 1\n"
"				contrast = 1.2\n"
"				tintColor = 1,1,1,0\n"
"				texTiling = 1024\n"
"				texPower = 0.75\n"
"				multiPower = 0.75\n"
"				groundTexStart = 0\n"
"				groundTexEnd = 20000\n"
"				multiFactor = 0.5\n"
"				mainTex = BUILTIN/RockyGround\n"
"				mainTexScale = 1,1\n"
"				mainTexOffset = 0,0\n"
"				planetOpacity = 1\n"
"			}\n"
"			Mods\n"
"			{\n"
"				VertexSimplexHeightAbsolute\n"
"				{\n"
"					deformity = 3000\n"
"					frequency = 2\n"
"					octaves = 6\n"
"					persistence = 0.5\n"
"					seed = 2312\n"
"					order = 20\n"
"					enabled = True\n"
"					name = _Height\n"
"				}\n"
"				VertexHeightNoise\n"
"				{\n"
"					deformity = 2600\n"
"					frequency = 1.5\n"
"					octaves = 4\n"
"					persistence = 0.5\n"
"					seed = 546345\n"
"					noiseType = RiggedMultifractal\n"
"					mode = Low\n"
"					lacunarity = 2.5\n"
"					order = 10\n"
"					enabled = True\n"
"					name = _Height\n"
"				}\n"
"				FlattenOcean\n"
"				{\n"
"					oceanRadius = 1\n"
"					order = 11\n"
"					enabled = True\n"
"					name = _Height\n"
"				}\n"
"				VertexSimplexHeightAbsolute\n"
"				{\n"
"					deformity = 800\n"
"					frequency = 6\n"
"					octaves = 8\n"
"					persistence = 0.5\n"
"					seed = 5645667\n"
"					order = 21\n"
"					enabled = True\n"
"					name = _Height\n"
"				}\n"
"				VertexHeightOffset\n"
"				{\n"
"					offset = -700\n"
"					order = 80\n"
"					enabled = True\n"
"					name = _Height\n"
"				}\n"
"				AltitudeAlpha\n"
"				{\n"
"					atmosphereDepth = 8000\n"
"					invert = False\n"
"					order = 999999999\n"
"					enabled = True\n"
"					name = _Material_ModProjection\n"
"				}\n"
"				VertexSimplexNoiseColor\n"
"				{\n"
"					blend = 1\n"
"					colorStart = 0.925373137,0.899681747,0.495042235,1\n"
"					colorEnd = 0.139860123,0.143785819,0.149253726,1\n"
"					frequency = 4\n"
"					octaves = 8\n"
"					persistence = 0.5\n"
"					seed = 9674345\n"
"					order = 40\n"
"					enabled = True\n"
"					name = _Color\n"
"				}\n"
"				HeightColorMap\n"
"				{\n"
"					blend = 0.5\n"
"					order = 41\n"
"					enabled = True\n"
"					name = _Color\n"
"					LandClasses\n"
"					{\n"
"						Value\n"
"						{\n"
"							name = AbyPl\n"
"							color = 1,0,0,1\n"
"							altitudeStart = 0\n"
"							altitudeEnd = 0.600000023841858\n"
"							lerpToNext = True\n"
"							delete = False\n"
"						}\n"
"						Value\n"
"						{\n"
"							name = Beach\n"
"							color = 0.656716406,0.458899528,0.401836962,1\n"
"							altitudeStart = 0.600000023841858\n"
"							altitudeEnd = 0.850000023841858\n"
"							lerpToNext = True\n"
"							delete = False\n"
"						}\n"
"						Value\n"
"						{\n"
"							name = Grass\n"
"							color = 0.477611959,0.477611959,0.477611959,1\n"
"							altitudeStart = 0.850000023841858\n"
"							altitudeEnd = 1\n"
"							lerpToNext = False\n"
"							delete = False\n"
"						}\n"
"					}\n"
"				}\n"
"				LandControl\n"
"				{\n"
"					altitudeBlend = 0\n"
"					altitudeFrequency = 1\n"
"					altitudeOctaves = 1\n"
"					altitudePersistance = 1\n"
"					altitudeSeed = 1\n"
"					createColors = False\n"
"					createScatter = True\n"
"					latitudeBlend = 0\n"
"					latitudeFrequency = 1\n"
"					latitudeOctaves = 1\n"
"					latitudePersistance = 1\n"
"					latitudeSeed = 1\n"
"					longitudeBlend = 0\n"
"					longitudeFrequency = 1\n"
"					longitudeOctaves = 1\n"
"					longitudePersistance = 1\n"
"					longitudeSeed = 1\n"
"					useHeightMap = False\n"
"					vHeightMax = 10000\n"
"					order = 999999\n"
"					enabled = True\n"
"					name = Scatter\n"
"					Scatters\n"
"					{\n"
"						Value\n"
"						{\n"
"							name = boulder\n"
"							materialType = DiffuseDetail\n"
"							material = BUILTIN/brownrock\n"
"							mesh = BUILTIN/boulder\n"
"							castShadows = True\n"
"							densityFactor = 1\n"
"							maxCache = 512\n"
"							maxCacheDelta = 32\n"
"							maxLevelOffset = 0\n"
"							maxScale = 2\n"
"							maxScatter = 20\n"
"							maxSpeed = 1000\n"
"							minScale = 0.25\n"
"							recieveShadows = True\n"
"							seed = 231123\n"
"							verticalOffset = -0.15\n"
"							instancing = False\n"
"							rotation = 0 360\n"
"							useBetterDensity = False\n"
"							spawnChance = 1\n"
"							ignoreDensityGameSetting = False\n"
"							densityVariance = -0.5 0.5\n"
"							delete = False\n"
"							Material\n"
"							{\n"
"								color = 0.664179087,0.63194412,0.448204786,1\n"
"								mainTex = BUILTIN/distantground\n"
"								mainTexScale = 0.5,0.5\n"
"								mainTexOffset = 0,0\n"
"								detail = BUILTIN/rock00\n"
"								detailScale = 3,3\n"
"								detailOffset = 0,0\n"
"							}\n"
"						}\n"
"						Value\n"
"						{\n"
"							name = stalactite\n"
"							materialType = DiffuseDetail\n"
"							material = BUILTIN/brownrock\n"
"							mesh = BUILTIN/Cube\n"
"							castShadows = True\n"
"							densityFactor = 1\n"
"							maxCache = 512\n"
"							maxCacheDelta = 32\n"
"							maxLevelOffset = 0\n"
"							maxScale = 4\n"
"							maxScatter = 20\n"
"							maxSpeed = 1000\n"
"							minScale = 0.5\n"
"							recieveShadows = True\n"
"							seed = 23453\n"
"							verticalOffset = 0\n"
"							instancing = False\n"
"							rotation = 0 360\n"
"							useBetterDensity = False\n"
"							spawnChance = 1\n"
"							ignoreDensityGameSetting = False\n"
"							densityVariance = -0.5 0.5\n"
"							delete = False\n"
"							Material\n"
"							{\n"
"								color = 0.664179087,0.63194412,0.448204786,1\n"
"								mainTex = BUILTIN/distantground\n"
"								mainTexScale = 0.5,0.5\n"
"								mainTexOffset = 0,0\n"
"								detail = BUILTIN/rock00\n"
"								detailScale = 3,3\n"
"								detailOffset = 0,0\n"
"							}\n"
"						}\n"
"					}\n"
"					LandClasses\n"
"					{\n"
"						Value\n"
"						{\n"
"							alterApparentHeight = 0\n"
"							alterRealHeight = 0\n"
"							color = 0,0,0,0\n"
"							coverageBlend = 0\n"
"							coverageFrequency = 1\n"
"							coverageOctaves = 1\n"
"							coveragePersistance = 1\n"
"							coverageSeed = 1\n"
"							name = Base\n"
"							latDelta = 1\n"
"							latitudeDouble = False\n"
"							lonDelta = 1\n"
"							minimumRealHeight = 0\n"
"							noiseBlend = 0\n"
"							noiseColor = 0,0,0,0\n"
"							noiseFrequency = 1\n"
"							noiseOctaves = 1\n"
"							noisePersistance = 1\n"
"							noiseSeed = 1\n"
"							delete = False\n"
"							altitudeRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							latitudeDoubleRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							latitudeRange\n"
"							{\n"
"								endEnd = 1\n"
"								endStart = 1\n"
"								startEnd = 0\n"
"								startStart = 0\n"
"							}\n"
"							longitudeRange\n"
"							{\n"
"								endEnd = 2\n"
"								endStart = 2\n"
"								startEnd = -1\n"
"								startStart = -1\n"
"							}\n"
"							Scatters\n"
"							{\n"
"								Value\n"
"								{\n"
"									density = 0.25\n"
"									scatterName = boulder\n"
"									delete = False\n"
"								}\n"
"								Value\n"
"								{\n"
"									density = 0.75\n"
"									scatterName = stalactite\n"
"									delete = False\n"
"								}\n"
"							}\n"
"						}\n"
"					}\n"
"				}\n"
"				City\n"
"				{\n"
"					debugOrientated = False\n"
"					frameDelta = 1\n"
"					randomizeOnSphere = True\n"
"					reorientToSphere = True\n"
"					reorientFinalAngle = 45\n"
"					reorientInitialUp = 0,1,0\n"
"					repositionRadial = 513856,-290549,-122798\n"
"					repositionRadiusOffset = 2948.5\n"
"					repositionToSphere = True\n"
"					repositionToSphereSurface = True\n"
"					repositionToSphereSurfaceAddHeight = False\n"
"					commnetStation = False\n"
"					isKSC = False\n"
"					order = 100\n"
"					enabled = True\n"
"					name = Randolith\n"
"					LOD\n"
"					{\n"
"						Value\n"
"						{\n"
"							visibleRange = 10000\n"
"							scale = 0,0,0\n"
"							delete = False\n"
"						}\n"
"					}\n"
"				}\n"
"			}\n"
"		}\n"
"		Debug\n"
"		{\n"
"			exportMesh = True // Whether Kopernicus should save a .bin file with the ScaledSpace mesh.\n"
"			update = False // Setting this to true will force Kopernicus to update the ScaledSpace mesh.\n"
"			showSOI = False\n"
"		}\n"
"	}\n"
"}\n";
#endif